(function(){
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const ri=(a,b)=>a+Math.floor(Math.random()*(b-a+1)), pick=a=>a[ri(0,a.length-1)];
  const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=ri(0,i);[a[i],a[j]]=[a[j],a[i]]}return a};
  const gcd=(a,b)=>{a=Math.abs(a);b=Math.abs(b);while(b){const t=a%b;a=b;b=t}return a||1};
  const frac=(n,d=1)=>{if(d<0){n=-n;d=-d}const g=gcd(n,d);n/=g;d/=g;return d===1?String(n):`${n}/${d}`};
  const sign=n=>n<0?`−${Math.abs(n)}`:`+${n}`;
  const sup=n=>['⁰','¹','²','³','⁴','⁵','⁶'][n]||`^${n}`;
  const choices=(correct,wrong)=>{const out=[];[correct,...wrong].forEach(x=>{x=String(x);if(!out.includes(x))out.push(x)});let i=1;while(out.length<4){const n=Number(correct),x=Number.isFinite(n)?String(n+i):`다른 값 ${i}`;if(!out.includes(x))out.push(x);i++}return shuffle(out.slice(0,4))};
  const Q=(equation,prompt,correct,wrong,explanation)=>({equation,prompt,correct:String(correct),choices:choices(correct,wrong),explanation});
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  const topics={
    real_roots:{code:'10',title:'방정식의 실근의 개수',desc:'삼차·사차함수의 개형을 이용해 방정식의 서로 다른 실근 수를 눈으로 판정합니다.',tag:'수능 실전',group:'derivative',formula:'f(x)=k의 실근 수 = y=f(x)와 y=k의 교점 수',theory:[['그래프로 번역','방정식을 한쪽으로 몰아 복잡하게 풀기보다, 함수 그래프와 수평선의 교점 문제로 바꿉니다.','f(x)=k ↔ 교점'],['극값이 경계','삼차함수에서는 극댓값과 극솟값이 실근 개수가 바뀌는 경계가 됩니다.','극솟값<k<극댓값'],['접하면 중근','수평선이 극값에서 접하면 중근이 생깁니다. 서로 다른 실근을 셀 때는 접점 하나로 셉니다.','접점 1개 = 서로 다른 근 1개']],trap:'대수식의 중복근을 서로 다른 실근 두 개로 세지 마세요.',tip:'먼저 극값의 높이를 구하고 k가 어느 높이에 있는지 비교하면 계산이 짧아집니다.',controls:[['k','수평선 높이 k',-3,3,.1,0]],labNote:'y=x³−3x의 극댓값은 2, 극솟값은 −2입니다.'},
    motion:{code:'11',title:'속도와 가속도',desc:'위치함수를 두 번 미분하며 위치·속도·가속도의 역할을 연결합니다.',tag:'교과 핵심',group:'derivative',formula:'v(t)=s′(t),  a(t)=v′(t)=s″(t)',theory:[['위치에서 속도','위치 s(t)의 순간변화율이 속도입니다. 그래프에서는 위치 그래프의 접선 기울기입니다.','v=s′'],['속도에서 가속도','속도의 순간변화율이 가속도입니다. 속도가 빨라지는지 방향이 바뀌는지 판단합니다.','a=v′'],['속도와 속력','속도는 방향을 포함해 음수가 될 수 있지만, 속력은 |v(t)|로 항상 0 이상입니다.','속력=|v|']],trap:'가속도의 부호와 물체가 빨라지는지를 항상 같은 뜻으로 해석하면 안 됩니다.',tip:'속도와 가속도의 부호가 같으면 속력이 증가하고, 다르면 속력이 감소합니다.',controls:[['a','삼차항 계수 a',1,3,1,1],['b','이차항 계수 b',-3,3,1,1],['t','관찰 시각 t',0,4,.1,2]],labNote:'s(t)=at³+bt²를 움직이며 같은 시각의 s, v, a를 비교하세요.'},
    cubic_ratio:{code:'12',title:'삼차함수와 이차함수의 비율 관계',desc:'삼차함수의 두 극점 사이 높이 차를 도함수의 근 간격만으로 계산하는 수능형 구조입니다.',tag:'수능 확장',group:'derivative',formula:'f′(x)=3a(x−α)(x−β) ⇒ |f(β)−f(α)|=|a|(β−α)³/2',theory:[['도함수부터 보기','삼차함수의 두 극점 α, β는 이차 도함수의 두 근입니다.','f′(α)=f′(β)=0'],['높이 차는 적분','f(β)−f(α)는 α부터 β까지 도함수를 적분한 값입니다.','Δf=∫[α→β]f′'],['간격의 세제곱','도함수 포물선의 폭이 d배가 되면 극값의 높이 차는 d³배가 됩니다.','높이 차 ∝ (β−α)³']],trap:'공식의 a는 원함수 ax³의 최고차항 계수입니다. 도함수 최고차항 3a와 구분하세요.',tip:'극점의 정확한 함숫값을 각각 계산하지 않고도 높이 차를 바로 구할 수 있습니다.',controls:[['a','최고차항 계수 a',1,3,1,1],['alpha','첫 임계점 α',-3,0,.5,-2],['d','두 근의 간격 β−α',1,4,.5,3]],labNote:'도함수의 두 근 사이 간격을 늘리면 높이 차가 세제곱으로 커집니다.'},
    lhopital:{code:'13',title:'로피탈 정리',desc:'0/0 또는 ∞/∞ 미정형에서 분자와 분모를 각각 미분해 극한을 계산하는 대학 맛보기입니다.',tag:'대학 맛보기',group:'derivative',formula:'0/0, ∞/∞에서  lim f/g = lim f′/g′',theory:[['미정형 확인','대입 결과가 반드시 0/0 또는 ∞/∞인지 먼저 확인해야 합니다.','조건 확인이 먼저'],['각각 미분','분수 전체를 몫의 미분법으로 미분하는 것이 아니라 분자와 분모를 따로 미분합니다.','f/g → f′/g′'],['필요하면 반복','한 번 적용한 뒤에도 미정형이면 조건을 다시 확인하고 반복할 수 있습니다.','매 단계 조건 재확인']],trap:'∞−∞, 0·∞ 같은 꼴에는 변형 없이 바로 적용할 수 없습니다.',tip:'고등학교 풀이에서는 인수분해·유리화·공식이 우선이며, 로피탈은 결과 확인용 확장 도구로 사용하세요.',controls:[['k','계수 k',1,5,1,3],['x','0에 가까운 x',.05,1,.05,.5]],labNote:'sin(kx)/x와 그 미분비 kcos(kx)가 x→0에서 같은 값 k로 가는 모습을 비교합니다.'},
    antiderivative:{code:'14',title:'부정적분과 원함수',desc:'미분의 반대 과정으로 원함수의 가족을 만들고 적분상수의 의미를 이해합니다.',tag:'교과 핵심',group:'integral',formula:'∫xⁿdx=xⁿ⁺¹/(n+1)+C  (n≠−1)',theory:[['미분을 거꾸로','부정적분은 미분했을 때 주어진 함수가 되는 모든 원함수를 찾는 과정입니다.','F′=f'],['지수 올리고 나누기','다항식은 지수를 하나 올린 뒤 그 새 지수로 계수를 나눕니다.','xⁿ→xⁿ⁺¹/(n+1)'],['적분상수 C','상수는 미분하면 0이므로 서로 다른 원함수들은 상수만큼 평행이동한 관계입니다.','F(x)+C']],trap:'부정적분의 답에서 +C를 빠뜨리면 원함수 하나만 나타냅니다.',tip:'답을 다시 미분해 원래 피적분함수가 나오는지 확인하면 실수를 바로 잡을 수 있습니다.',controls:[['a','계수 a',1,5,1,2],['n','지수 n',1,4,1,2],['c','적분상수 C',-3,3,1,0]],labNote:'C를 바꾸면 원함수 그래프는 위아래로 움직이지만 도함수는 변하지 않습니다.'},
    definite_integral:{code:'15',title:'정적분의 계산과 성질',desc:'원시함수의 위끝값과 아래끝값의 차로 누적된 부호 있는 양을 계산합니다.',tag:'교과 핵심',group:'integral',formula:'∫[a→b]f(x)dx=F(b)−F(a)',theory:[['위끝−아래끝','피적분함수의 원시함수 F를 구한 뒤 F(b)에서 F(a)를 뺍니다.','F(b)−F(a)'],['부호 있는 넓이','x축 위 영역은 양수, 아래 영역은 음수로 더해집니다.','정적분≠항상 넓이'],['구간 성질','구간을 나눠 더하거나 적분구간의 순서를 바꿔 부호를 바꿀 수 있습니다.','∫a→c+∫c→b=∫a→b']],trap:'아래끝값 앞의 마이너스를 괄호 전체에 분배하세요.',tip:'적분값이 음수여도 계산이 틀린 것은 아닙니다. 넓이를 묻는지 먼저 확인하세요.',controls:[['a','직선의 기울기 a',-3,3,1,1],['b','y절편 b',-3,3,1,0],['u','위끝 u',1,5,.5,4]],labNote:'f(x)=ax+b를 0부터 u까지 적분한 부호 있는 영역을 확인하세요.'},
    integral_function:{code:'16',title:'정적분으로 정의된 함수',desc:'누적량으로 정의된 함수의 값과 변화율을 미적분의 기본정리로 연결합니다.',tag:'수능 실전',group:'integral',formula:'F(x)=∫[a→x]f(t)dt ⇒ F′(x)=f(x)',theory:[['누적함수 F','F(x)는 a부터 x까지 쌓인 부호 있는 넓이를 함수값으로 갖습니다.','F(x)=누적량'],['순간변화율','위끝 x가 조금 움직일 때 새로 더해지는 얇은 넓이의 높이가 f(x)입니다.','F′(x)=f(x)'],['합성된 위끝','위끝이 g(x)이면 연쇄법칙으로 g′(x)를 추가로 곱합니다.','d/dx ∫a→g(x)f=f(g(x))g′']],trap:'적분 안의 문자 t는 임시 변수입니다. F′(x)를 구할 때 x를 대입합니다.',tip:'F의 증가·감소는 f의 부호, F의 극값은 f의 부호 변화로 판정할 수 있습니다.',controls:[['a','이차항 계수 a',1,4,1,1],['b','상수항 b',-3,3,1,-1],['x','관찰 위치 x',0,4,.1,2]],labNote:'F(x)=∫₀ˣ(at²+b)dt와 F′(x)=ax²+b를 동시에 비교하세요.'},
    area_integral:{code:'17',title:'정적분과 넓이',desc:'함수의 부호와 두 그래프의 위아래를 판단해 실제 넓이를 정적분으로 계산합니다.',tag:'교과 핵심',group:'integral',formula:'넓이 = ∫|f(x)|dx 또는 ∫|f(x)−g(x)|dx',theory:[['x축과의 넓이','함수가 음수인 구간에서는 정적분값의 부호를 바꾸어 양의 넓이로 더합니다.','∫|f|'],['두 곡선 사이','각 구간에서 위 함수−아래 함수를 적분합니다. 교점에서 위아래가 바뀔 수 있습니다.','∫(위−아래)'],['구간 분할','x축과의 교점 또는 두 곡선의 교점을 기준으로 적분구간을 나눕니다.','교점이 경계']],trap:'정적분값에 무조건 절댓값 하나만 씌우면 여러 구간의 넓이가 상쇄될 수 있습니다.',tip:'그래프를 간단히 스케치하고 부호표를 만든 뒤 적분식을 세우세요.',controls:[['k','기울기 k',1,4,1,2],['r','x축과의 교점 r',1,4,.5,2]],labNote:'y=k(x−r)를 0부터 2r까지 보면 정적분은 0이지만 실제 넓이는 양수입니다.'},
    velocity_distance:{code:'18',title:'속도와 이동거리',desc:'속도의 부호 변화를 기준으로 변위와 총 이동거리를 구분해 적분합니다.',tag:'교과 핵심',group:'integral',formula:'변위=∫v(t)dt,  이동거리=∫|v(t)|dt',theory:[['변위','출발점에서 도착점까지의 위치 변화량입니다. 반대 방향 이동은 음수로 상쇄됩니다.','Δs=∫v'],['이동거리','실제로 움직인 전체 길이이므로 속력 |v|를 적분합니다.','거리=∫|v|'],['방향 전환','v(t)=0이면서 부호가 바뀌는 시각에서 적분구간을 나눕니다.','v=0을 먼저 찾기']],trap:'전체 변위에 한 번 절댓값을 씌운 값은 총 이동거리와 다를 수 있습니다.',tip:'속도 그래프와 t축 사이의 위쪽·아래쪽 넓이를 각각 양수로 더하면 이동거리입니다.',controls:[['k','방향 전환 시각 k',1,4,.5,2],['t','관찰 시각 t',0,8,.1,1]],labNote:'v(t)=2(t−k)를 0부터 2k까지 보면 변위는 0이지만 이동거리는 2k²입니다.'}
  };
  const id=document.body.dataset.calcTopic,topic=topics[id],app=$('#topicApp');
  if(!topic){app.innerHTML='<p>학습 주제를 찾을 수 없습니다.</p>';return}
  const palettes={derivative:['#2B6CA3','#173E5E','#EAF1F6'],integral:['#7A4E8C','#493055','#F3EDF6']};
  const palette=palettes[topic.group];document.documentElement.style.setProperty('--accent',palette[0]);document.documentElement.style.setProperty('--accent-dark',palette[1]);document.documentElement.style.setProperty('--soft',palette[2]);
  const backHash=topic.group==='integral'?'integral':'derivative';
  app.innerHTML=`<div class="topic-page"><nav class="topic-nav"><div class="topic-nav-inner"><a class="topic-back" href="미적분1.html#${backHash}" aria-label="미적분 목록으로">←</a><button class="topic-tab active" data-tab="theory"><span>01</span>원리</button><button class="topic-tab" data-tab="lab"><span>02</span>실험실</button><button class="topic-tab game" data-tab="game"><span>03</span>스릴 아레나</button></div></nav><main class="topic-wrap">
    <section data-panel="theory"><header class="topic-hero"><div><p class="topic-kicker">${String(topic.code).padStart(2,'0')} · ${topic.group==='integral'?'적분':'미분의 활용'}</p><h1>${topic.title}</h1><p class="desc">${topic.desc}</p></div><span class="topic-badge">${topic.tag}</span></header><div class="core-formula"><span>CORE IDEA</span><strong>${topic.formula}</strong></div><div class="theory-grid">${topic.theory.map((x,i)=>`<article class="theory-card"><em>${i+1}</em><h2>${x[0]}</h2><p>${x[1]}</p><div class="mini-formula">${x[2]}</div></article>`).join('')}</div><div class="check-strip"><article class="check-card trap"><strong>자주 하는 실수</strong><p>${topic.trap}</p></article><article class="check-card tip"><strong>실전 사용법</strong><p>${topic.tip}</p></article></div></section>
    <section class="hidden" data-panel="lab"><header class="section-hero"><p class="topic-kicker">INTERACTIVE LAB</p><h1>${topic.title} 실험실</h1><p class="desc">슬라이더를 움직여 식, 그래프, 계산값이 함께 변하는 모습을 확인하세요.</p></header><div class="lab-layout"><div class="canvas-card"><canvas id="labCanvas" width="760" height="450"></canvas><div class="graph-legend"><span><i class="a"></i>주 함수</span><span><i class="b"></i>비교 함수·기준선</span><span><i class="c"></i>관찰 지점</span></div></div><aside class="lab-control-card"><h2>변수 조종실</h2><p>${topic.labNote}</p><div data-lab-controls>${topic.controls.map(c=>`<label class="lab-range"><span>${c[1]} <output data-output="${c[0]}">${c[5]}</output></span><input data-control="${c[0]}" type="range" min="${c[2]}" max="${c[3]}" step="${c[4]}" value="${c[5]}"></label>`).join('')}</div><div class="lab-readouts" data-readouts></div><div class="lab-note" data-lab-note></div></aside></div></section>
    <section class="hidden" data-panel="game"><header class="section-hero"><p class="topic-kicker">THRILL ARENA</p><h1>${topic.title} 아레나</h1><p class="desc">문제당 10초. 혼자 기록에 도전하거나 친구와 같은 8문제로 겨뤄보세요.</p></header><div class="game-shell"><div class="game-setup" data-game-setup><div class="player-fields"><label>PLAYER 1<input data-p1 value="나" maxlength="10"></label><label>PLAYER 2<input data-p2 value="친구" maxlength="10"></label></div><div class="mode-grid"><button class="mode-card" data-mode="solo"><span>SOLO RECORD</span><b>혼자 기록전</b><small>8문제·3라이프·콤보 점수로 TOP 5에 도전합니다.</small></button><button class="mode-card duel" data-mode="duel"><span>FRIEND 1:1</span><b>친구와 대결</b><small>같은 기기에서 같은 8문제를 차례로 풉니다.</small></button></div><div class="leaderboard"><h3>이 기기 TOP 5</h3><ol data-leaders></ol></div></div><div class="game-play hidden" data-game-play><div class="game-hud"><div class="hud-cell"><span>PLAYER</span><strong data-player>—</strong></div><div class="hud-cell"><span>ROUND</span><strong data-round>1/8</strong></div><div class="hud-cell"><span>SCORE</span><strong data-score>0</strong></div><div class="hud-cell"><span>COMBO · LIFE</span><strong data-combo>×1 · ♥♥♥</strong></div></div><div class="timer-track"><div data-timer></div></div><div class="game-question"><div class="equation" data-game-equation></div><h2 data-game-prompt></h2></div><div class="game-choices" data-game-choices></div><div class="game-feedback hidden" data-game-feedback></div></div><div class="handoff hidden" data-handoff><h2><span data-next-name></span> 차례!</h2><p data-handoff-copy></p><button class="game-button" data-next-player>두 번째 선수 시작</button></div><div class="game-result hidden" data-game-result></div></div></section>
  </main></div>`;

  let arenaRunning=false,arenaRaf=0;
  function showTab(name){if(name!=='game'&&arenaRunning)stopTimer();$$('[data-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==name));$$('.topic-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));if(name==='lab')updateLab();window.scrollTo({top:0,behavior:'smooth'})}
  $$('.topic-tab').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));

  const canvas=$('#labCanvas'),ctx=canvas.getContext('2d');
  function chart(series,opt={}){
    const W=canvas.width,H=canvas.height,pad=48,xmin=opt.xmin??-4,xmax=opt.xmax??4;let ymin=opt.ymin,ymax=opt.ymax;
    if(ymin==null||ymax==null){const vals=[];series.forEach(s=>{for(let i=0;i<=180;i++){const x=xmin+(xmax-xmin)*i/180,y=s.f(x);if(Number.isFinite(y))vals.push(y)}});ymin=Math.min(-1,...vals);ymax=Math.max(1,...vals);const span=Math.max(2,ymax-ymin);ymin-=span*.12;ymax+=span*.12}
    const X=x=>pad+(x-xmin)/(xmax-xmin)*(W-2*pad),Y=y=>H-pad-(y-ymin)/(ymax-ymin)*(H-2*pad);
    ctx.clearRect(0,0,W,H);ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#E3E8E5';ctx.lineWidth=1;
    for(let i=0;i<=8;i++){const x=pad+(W-2*pad)*i/8;ctx.beginPath();ctx.moveTo(x,pad);ctx.lineTo(x,H-pad);ctx.stroke()}for(let i=0;i<=6;i++){const y=pad+(H-2*pad)*i/6;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(W-pad,y);ctx.stroke()}
    ctx.strokeStyle='#7C8983';ctx.lineWidth=1.4;ctx.beginPath();if(ymin<=0&&ymax>=0){ctx.moveTo(pad,Y(0));ctx.lineTo(W-pad,Y(0))}if(xmin<=0&&xmax>=0){ctx.moveTo(X(0),pad);ctx.lineTo(X(0),H-pad)}ctx.stroke();
    series.forEach(s=>{if(s.fill){ctx.beginPath();ctx.moveTo(X(xmin),Y(0));for(let i=0;i<=260;i++){const x=xmin+(xmax-xmin)*i/260,y=s.f(x);if(Number.isFinite(y))ctx.lineTo(X(x),Y(y))}ctx.lineTo(X(xmax),Y(0));ctx.closePath();ctx.fillStyle=s.fill;ctx.fill()};ctx.beginPath();let on=false;for(let i=0;i<=300;i++){const x=xmin+(xmax-xmin)*i/300,y=s.f(x);if(!Number.isFinite(y)||y<ymin*3-10||y>ymax*3+10){on=false;continue}if(!on){ctx.moveTo(X(x),Y(y));on=true}else ctx.lineTo(X(x),Y(y))}ctx.strokeStyle=s.color||palette[0];ctx.lineWidth=s.width||3;ctx.stroke()});
    (opt.lines||[]).forEach(l=>{ctx.strokeStyle=l.color||'#C1442D';ctx.setLineDash(l.dash?[6,5]:[]);ctx.lineWidth=2;ctx.beginPath();if(l.x!=null){ctx.moveTo(X(l.x),pad);ctx.lineTo(X(l.x),H-pad)}else{ctx.moveTo(pad,Y(l.y));ctx.lineTo(W-pad,Y(l.y))}ctx.stroke();ctx.setLineDash([])});
    (opt.points||[]).forEach(pt=>{ctx.fillStyle=pt.color||'#C99A2E';ctx.beginPath();ctx.arc(X(pt.x),Y(pt.y),5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#223027';ctx.font='12px sans-serif';ctx.fillText(pt.label||'',X(pt.x)+8,Y(pt.y)-8)});
  }
  const values=()=>Object.fromEntries($$('[data-control]').map(x=>[x.dataset.control,+x.value]));
  function setReadouts(items,note){$('[data-readouts]').innerHTML=items.map((x,i)=>`<div class="lab-readout ${i===items.length-1&&items.length%2?'wide':''}"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('[data-lab-note]').textContent=note}
  function updateLab(){
    const v=values();$$('[data-output]').forEach(o=>o.textContent=v[o.dataset.output]);let a,b,x,k,r,d,beta,F,vel,acc,integral,area;
    switch(id){
      case'real_roots':k=v.k;chart([{f:x=>x*x*x-3*x,color:palette[0]},{f:()=>k,color:'#C1442D'}],{xmin:-3,xmax:3,ymin:-4,ymax:4,lines:[{y:k,color:'#C1442D',dash:true}]});r=Math.abs(k)<2?3:Math.abs(k)===2?2:1;setReadouts([['극댓값','2'],['극솟값','−2'],['서로 다른 실근',r+'개']],`k=${k}일 때 수평선과 그래프가 ${r}번 만납니다.`);break;
      case'motion':a=v.a;b=v.b;x=v.t;F=t=>a*t*t*t+b*t*t;vel=3*a*x*x+2*b*x;acc=6*a*x+2*b;chart([{f:F,color:palette[0]},{f:t=>3*a*t*t+2*b*t,color:'#C1442D'}],{xmin:0,xmax:4,points:[{x,y:F(x),label:'s(t)'},{x,y:vel,label:'v(t)',color:'#C1442D'}]});setReadouts([['위치 s(t)',F(x).toFixed(2)],['속도 v(t)',vel.toFixed(2)],['가속도 a(t)',acc.toFixed(2)]],`t=${x}에서 속도와 가속도의 부호가 ${Math.sign(vel)===Math.sign(acc)?'같아 속력이 증가':'달라 속력이 감소'}합니다.`);break;
      case'cubic_ratio':a=v.a;x=v.alpha;d=v.d;beta=x+d;F=t=>a*t*t*t-1.5*a*(x+beta)*t*t+3*a*x*beta*t;chart([{f:F,color:palette[0]},{f:t=>3*a*(t-x)*(t-beta),color:'#C1442D'}],{xmin:x-1.5,xmax:beta+1.5,points:[{x,y:F(x),label:'α'},{x:beta,y:F(beta),label:'β'}],lines:[{x},{x:beta}]});setReadouts([['α',x],['β',beta],['|극값의 차|',(a*d*d*d/2).toFixed(2)]],`간격 ${d}의 세제곱에 비례하여 높이 차가 ${a*d*d*d/2}가 됩니다.`);break;
      case'lhopital':k=v.k;x=v.x;chart([{f:t=>Math.abs(t)<.015?NaN:Math.sin(k*t)/t,color:palette[0]},{f:t=>k*Math.cos(k*t),color:'#C1442D'}],{xmin:-1.2,xmax:1.2,ymin:-1,ymax:k+1,points:[{x,y:Math.sin(k*x)/x,label:'원래 비'}]});setReadouts([['sin(kx)/x',(Math.sin(k*x)/x).toFixed(4)],['kcos(kx)',(k*Math.cos(k*x)).toFixed(4)],['x→0의 극한',k]],`x=${x}가 0에 가까워질수록 두 값이 ${k}에 가까워집니다.`);break;
      case'antiderivative':a=v.a;k=v.n;r=v.c;F=x=>a*Math.pow(x,k+1)/(k+1)+r;chart([{f:F,color:palette[0]},{f:x=>a*Math.pow(x,k),color:'#C1442D'}],{xmin:-2.5,xmax:2.5});setReadouts([['피적분함수',`${a}x${sup(k)}`],['원함수',`${frac(a,k+1)}x${sup(k+1)}${r?sign(r):''}`],['적분상수 C',r]],'C를 움직여도 두 그래프의 기울기 관계는 그대로입니다.');break;
      case'definite_integral':a=v.a;b=v.b;r=v.u;integral=a*r*r/2+b*r;chart([{f:x=>a*x+b,color:palette[0],fill:'rgba(43,108,163,.14)'}],{xmin:0,xmax:Math.max(5,r),lines:[{x:r,color:'#C99A2E'}]});setReadouts([['원시함수',`${frac(a,2)}x²${b?sign(b)+'x':''}`],['적분구간',`0 → ${r}`],['정적분값',integral.toFixed(2)]],`x축 아래 영역은 음수로 합산한 결과가 ${integral.toFixed(2)}입니다.`);break;
      case'integral_function':a=v.a;b=v.b;x=v.x;F=t=>a*t*t*t/3+b*t;vel=a*x*x+b;chart([{f:F,color:palette[0]},{f:t=>a*t*t+b,color:'#C1442D'}],{xmin:0,xmax:4,points:[{x,y:F(x),label:'F(x)'},{x,y:vel,label:'F′(x)',color:'#C1442D'}]});setReadouts([['누적값 F(x)',F(x).toFixed(3)],['F′(x)',vel.toFixed(3)],['피적분함수 값',vel.toFixed(3)]],'F′(x)와 피적분함수의 x에서의 값이 정확히 같습니다.');break;
      case'area_integral':k=v.k;r=v.r;F=x=>k*(x-r);chart([{f:F,color:palette[0],fill:'rgba(122,78,140,.16)'}],{xmin:0,xmax:2*r,lines:[{x:r,color:'#C99A2E'}]});area=k*r*r;setReadouts([['부호 있는 정적분','0'],['왼쪽 넓이',area/2],['전체 실제 넓이',area]],`음수 영역과 양수 영역은 상쇄되지만 실제 넓이는 ${area}입니다.`);break;
      case'velocity_distance':k=v.k;x=Math.min(v.t,2*k);F=t=>2*(t-k);chart([{f:F,color:palette[0],fill:'rgba(122,78,140,.16)'}],{xmin:0,xmax:2*k,lines:[{x:k,color:'#C99A2E'}],points:[{x,y:F(x),label:'v(t)'}]});setReadouts([['현재 속도',F(x).toFixed(2)],['전체 변위','0'],['총 이동거리',2*k*k]],`t=${k}에서 방향을 바꾸며, 0부터 ${2*k}까지 이동거리는 ${2*k*k}입니다.`);break;
    }
  }
  $$('[data-control]').forEach(x=>x.addEventListener('input',updateLab));

  function makeQuestion(){let a,b,k,c,t,d,correct,n;
    switch(id){
      case'real_roots':k=pick([-3,-2,-1,0,1,2,3]);correct=Math.abs(k)<2?'3개':Math.abs(k)===2?'2개':'1개';return Q(`x³−3x=${k}`,'서로 다른 실근의 개수는?',correct,['1개','2개','3개','0개'].filter(x=>x!==correct),`극댓값 2와 극솟값 −2 사이의 높이인지 비교합니다.`);
      case'motion':a=ri(1,3);b=ri(1,4);t=ri(1,3);correct=3*a*t*t+2*b*t;return Q(`s(t)=${a}t³+${b}t²`,'t='+t+'에서 속도는?',correct,[a*t*t+b*t,6*a*t+2*b,3*a*t+2*b],`s를 한 번 미분한 v(t)=3${a}t²+2${b}t에 대입합니다.`);
      case'cubic_ratio':a=ri(1,3);d=ri(1,4);correct=frac(a*d*d*d,2);return Q(`f′(x)=3·${a}(x−α)(x−β), β−α=${d}`,'|f(β)−f(α)|는?',correct,[a*d*d,a*d*d*d,frac(3*a*d*d*d,2)],`공식 |a|(β−α)³/2를 적용하면 ${correct}입니다.`);
      case'lhopital':k=ri(1,6);return Q(`lim x→0  sin(${k}x)/x`,'로피탈 정리로 구한 값은?',k,[0,1,-k],`분자와 분모를 각각 미분하면 ${k}cos(${k}x)이므로 ${k}입니다.`);
      case'antiderivative':n=ri(1,4);k=ri(1,4);a=k*(n+1);correct=`${k===1?'':k}x${sup(n+1)}+C`;return Q(`∫ ${a}x${sup(n)} dx`,'부정적분은?',correct,[`${a}x${sup(n+1)}+C`,`${k}x${sup(n)}+C`,`${a*n}x${sup(Math.max(1,n-1))}+C`],`지수를 하나 올리고 ${n+1}로 나눕니다.`);
      case'definite_integral':a=2*ri(1,4);b=ri(1,5);correct=a*b*b/2;return Q(`∫[0→${b}] ${a}x dx`,'정적분값은?',correct,[a*b,a*b*b,correct-b],`원시함수 ${a/2}x²에 위끝과 아래끝을 대입합니다.`);
      case'integral_function':a=ri(1,4);b=ri(-3,3);c=ri(1,4);correct=a*c*c+b;return Q(`F(x)=∫[0→x](${a}t²${b?sign(b):''})dt`,'F′('+c+')의 값은?',correct,[frac(a*c*c*c,3)+b*c,2*a*c+b,a*c+b],`기본정리에 따라 F′(x)=${a}x²${b?sign(b):''}입니다.`);
      case'area_integral':k=ri(1,4);c=ri(1,4);correct=k*c*c;return Q(`y=${k}(x−${c}), 0≤x≤${2*c}`,'그래프와 x축 사이 전체 넓이는?',correct,[0,2*correct,frac(correct,2)],`두 합동 삼각형의 넓이를 더하면 ${correct}입니다.`);
      case'velocity_distance':k=ri(1,4);correct=2*k*k;return Q(`v(t)=2t−${2*k}, 0≤t≤${2*k}`,'총 이동거리는?',correct,[0,k*k,4*k*k],`t=${k}에서 나눈 두 삼각형 넓이의 합은 ${correct}입니다.`);
    }
  }

  const leaderKey=`jp-topic-leaders-${id}`;let leaders=[];try{leaders=JSON.parse(localStorage.getItem(leaderKey)||'[]')}catch(e){}
  function renderLeaders(){const ol=$('[data-leaders]');ol.innerHTML=leaders.length?leaders.slice(0,5).map(x=>`<li>${esc(x.name)} · ${x.score}점</li>`).join(''):'<li>아직 기록이 없습니다.</li>'}
  renderLeaders();
  let game={mode:'solo',questions:[],playerIndex:0,names:[],scores:[0,0],round:0,combo:0,lives:3,time:10,last:0,answered:false};
  function stopTimer(){arenaRunning=false;cancelAnimationFrame(arenaRaf)}
  function startGame(mode){game={mode,questions:Array.from({length:8},makeQuestion),playerIndex:0,names:[$('[data-p1]').value.trim()||'나',$('[data-p2]').value.trim()||'친구'],scores:[0,0],round:0,combo:0,lives:3,time:10,last:performance.now(),answered:false};$('[data-game-setup]').classList.add('hidden');$('[data-game-result]').classList.add('hidden');$('[data-handoff]').classList.add('hidden');$('[data-game-play]').classList.remove('hidden');nextGameQuestion()}
  $$('[data-mode]').forEach(b=>b.addEventListener('click',()=>startGame(b.dataset.mode)));
  function nextGameQuestion(){if(game.round>=8||game.lives<=0){finishPlayer();return}game.time=10;game.last=performance.now();game.answered=false;const q=game.questions[game.round];$('[data-player]').textContent=game.names[game.playerIndex];$('[data-round]').textContent=`${game.round+1}/8`;$('[data-score]').textContent=game.scores[game.playerIndex];$('[data-combo]').textContent=`×${1+Math.floor(game.combo/3)*.5} · ${'♥'.repeat(game.lives)}${'♡'.repeat(3-game.lives)}`;$('[data-game-equation]').textContent=q.equation;$('[data-game-prompt]').textContent=q.prompt;$('[data-game-feedback]').className='game-feedback hidden';const box=$('[data-game-choices]');box.innerHTML='';q.choices.forEach(v=>{const b=document.createElement('button');b.className='game-choice';b.textContent=v;b.addEventListener('click',()=>answerGame(v,b));box.appendChild(b)});stopTimer();arenaRunning=true;game.last=performance.now();arenaRaf=requestAnimationFrame(tickGame)}
  function tickGame(now){if(!arenaRunning)return;game.time=Math.max(0,game.time-(now-game.last)/1000);game.last=now;$('[data-timer]').style.width=`${game.time/10*100}%`;if(game.time<=0){answerGame(null,null);return}arenaRaf=requestAnimationFrame(tickGame)}
  function answerGame(value,button){if(game.answered)return;game.answered=true;stopTimer();const q=game.questions[game.round],ok=String(value)===q.correct;$$('.game-choice').forEach(b=>{b.disabled=true;if(b.textContent===q.correct)b.classList.add('correct')});if(!ok&&button)button.classList.add('wrong');const fb=$('[data-game-feedback]');if(ok){game.combo++;const mult=1+Math.floor(game.combo/3)*.5;game.scores[game.playerIndex]+=Math.round((100+game.time*10)*mult);fb.textContent=`정답! ${q.explanation}`;fb.className='game-feedback good'}else{game.combo=0;game.lives--;fb.textContent=(value==null?'시간 초과! ':'오답! ')+q.explanation;fb.className='game-feedback bad'}game.round++;$('[data-score]').textContent=game.scores[game.playerIndex];setTimeout(nextGameQuestion,650)}
  function finishPlayer(){stopTimer();$('[data-game-play]').classList.add('hidden');if(game.mode==='duel'&&game.playerIndex===0){$('[data-next-name]').textContent=game.names[1];$('[data-handoff-copy]').textContent=`${game.names[0]}의 점수는 ${game.scores[0]}점입니다. 화면을 넘겨주세요.`;$('[data-handoff]').classList.remove('hidden');return}finishGame()}
  $('[data-next-player]').addEventListener('click',()=>{game.playerIndex=1;game.round=0;game.combo=0;game.lives=3;$('[data-handoff]').classList.add('hidden');$('[data-game-play]').classList.remove('hidden');nextGameQuestion()});
  function finishGame(){const box=$('[data-game-result]');let html;if(game.mode==='solo'){leaders.push({name:game.names[0],score:game.scores[0]});leaders.sort((a,b)=>b.score-a.score);leaders=leaders.slice(0,5);try{localStorage.setItem(leaderKey,JSON.stringify(leaders))}catch(e){}renderLeaders();html=`<div class="score">${game.scores[0]}</div><h2>${esc(game.names[0])} 기록 완료</h2><p>TOP 5 기록에 저장했습니다.</p>`}else{const win=game.scores[0]===game.scores[1]?'무승부':game.scores[0]>game.scores[1]?`${esc(game.names[0])} 승리!`:`${esc(game.names[1])} 승리!`;html=`<div class="score">${game.scores[0]} : ${game.scores[1]}</div><h2>${win}</h2><p>같은 8문제로 진행한 대결이 끝났습니다.</p>`}box.innerHTML=html+'<button class="game-button" data-rematch>다시 도전</button><button class="game-button secondary" data-setup>모드 선택</button>';box.classList.remove('hidden');$('[data-rematch]',box).addEventListener('click',()=>startGame(game.mode));$('[data-setup]',box).addEventListener('click',resetGame)}
  function resetGame(){stopTimer();$('[data-game-result]').classList.add('hidden');$('[data-game-play]').classList.add('hidden');$('[data-handoff]').classList.add('hidden');$('[data-game-setup]').classList.remove('hidden')}
})();
