(function(){
  'use strict';
  const G=window.GeoLab,lab=document.querySelector('[data-page="lab"]'),oldSvg=document.getElementById('genericLabSvg');
  if(!G||!lab||!oldSvg)return;
  lab.classList.add('position-direct-lab');lab.querySelector('.eyebrow').textContent='위치벡터 LAB · DIRECT MANIPULATION';lab.querySelector('h1').textContent='점의 이동을 화살표의 성분으로 읽어 보세요';lab.querySelector('.desc').textContent='끝점을 끌면 좌표와 벡터의 성분, 크기가 같은 순간 함께 변합니다. 두 점 모드에서는 시점과 종점을 모두 움직일 수 있습니다.';
  const layout=lab.querySelector('.lab-layout'),visual=layout.querySelector('.visual-card'),readouts=layout.querySelector('[data-readouts]'),controls=layout.querySelector('[data-controls]'),oldChips=lab.querySelector('[data-mode-chips]'),chips=oldChips.cloneNode(true);oldChips.replaceWith(chips);
  [...chips.querySelectorAll('.chip')].forEach(function(b,i){b.dataset.positionMode=i===0?'position':'displacement';});
  const tabs=document.createElement('div');tabs.className='position-mission-tabs';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','위치벡터 실험 모드');tabs.innerHTML='<button class="position-mission-tab active" data-position-mission="free">자유 실험</button><button class="position-mission-tab" data-position-mission="point">목표 좌표</button><button class="position-mission-tab" data-position-mission="vector">성분 벡터</button>';
  const brief=document.createElement('div');brief.className='position-mission-brief';brief.innerHTML='<div class="position-mission-kicker" data-position-kicker>FREE LAB</div><div class="position-mission-copy"><div><strong data-position-title>끝점을 직접 움직여 보세요.</strong><p data-position-copy>위치벡터에서는 점 P의 좌표가 곧 OP의 성분이 됩니다.</p></div><button class="position-next hidden" data-position-next>새 목표</button></div><div class="position-meter" data-position-meter></div>';chips.before(tabs,brief);
  const svg=oldSvg.cloneNode(false);oldSvg.replaceWith(svg);svg.classList.add('position-direct-stage');svg.setAttribute('aria-label','점과 벡터의 끝점을 직접 끌어 좌표와 성분을 확인하는 실험');visual.classList.add('position-stage-card');const guide=document.createElement('div');guide.className='position-drag-guide';guide.innerHTML='<span>●</span> 빛나는 점을 직접 끌어 보세요';visual.prepend(guide);
  readouts.classList.add('position-readout');readouts.innerHTML='<div class="readout-box"><div class="readout-label">시점과 종점</div><div class="readout-value" id="positionPoints"></div></div><div class="readout-box"><div class="readout-label">벡터의 성분</div><div class="readout-value" id="positionComponents"></div></div><div class="readout-box"><div class="readout-label">성분 계산</div><div class="readout-value" id="positionSubtract"></div></div><div class="readout-box"><div class="readout-label">벡터의 크기</div><div class="readout-value" id="positionMagnitude"></div></div>';controls.className='position-controls';controls.innerHTML='<button type="button" class="position-reset" data-position-reset>점 위치 초기화</button>';
  const pointTargets=[[4,-2],[-3,3],[2,4],[-4,-3],[1,-4]],vectorTargets=[[4,3],[-3,2],[2,-4],[-4,-1],[1,5]];const state={mode:'position',A:[0,0],B:[3,2],mission:'free',targetIndex:0,target:[4,-2],trails:{A:[],B:[]}};const colors={A:'#c1442d',B:'#2b6ca3',vector:'#2f7d58',ghost:'#7557a8'};let dragging=null;
  function vec(){return[state.B[0]-state.A[0],state.B[1]-state.A[1]];}
  function fmt(v){return '('+v.join(', ')+')';}
  function add(tag,attrs,text){const n=G.s(tag,attrs,text);svg.appendChild(n);return n;}
  function defs(){const d=G.s('defs');[['posVector',colors.vector],['posGhost',colors.ghost]].forEach(function(pair){const marker=G.s('marker',{id:pair[0],viewBox:'0 0 10 10',refX:8,refY:5,markerWidth:7,markerHeight:7,orient:'auto-start-reverse'});marker.appendChild(G.s('path',{d:'M0 0L10 5L0 10Z',fill:pair[1]}));d.appendChild(marker);});const glow=G.s('filter',{id:'positionGlow',x:'-90%',y:'-90%',width:'280%',height:'280%'});glow.appendChild(G.s('feGaussianBlur',{stdDeviation:5,result:'blur'}));const merge=G.s('feMerge');merge.appendChild(G.s('feMergeNode',{in:'blur'}));merge.appendChild(G.s('feMergeNode',{in:'SourceGraphic'}));glow.appendChild(merge);d.appendChild(glow);svg.appendChild(d);}
  function handle(g,name,p,color,enabled){const x=g.sx(p[0]),y=g.sy(p[1]),locked=!enabled;add('circle',{cx:x,cy:y,r:44,fill:'transparent','data-position-point':name,class:'position-point-hit'+(locked?' position-locked':'')});add('circle',{cx:x,cy:y,r:17,fill:color,opacity:.2,'data-position-point':name,class:'position-point-halo'+(locked?' position-locked':''),filter:'url(#positionGlow)'});add('circle',{cx:x,cy:y,r:11,fill:color,stroke:'#fff','stroke-width':3,'data-position-point':name,class:'position-point-handle'+(locked?' position-locked':'')});add('circle',{cx:x,cy:y,r:3,fill:'#fff','pointer-events':'none'});add('text',{x:x+(name==='A'?-13:13),y:y-13,'text-anchor':name==='A'?'end':'start',fill:color,'font-size':13,'font-weight':900,'pointer-events':'none'},name);}
  function trail(g,list,color){list.forEach(function(p,i){add('circle',{cx:g.sx(p[0]),cy:g.sy(p[1]),r:2.5+i*.5,fill:color,opacity:(i+1)/(list.length+1)*.3,'pointer-events':'none'});});}
  function draw(){G.clear(svg);const g=G.cartesian(svg,{xmin:-6,xmax:6,ymin:-5,ymax:5});g.grid();defs();trail(g,state.trails.A,colors.A);trail(g,state.trails.B,colors.B);const v=vec();
    if(state.mission==='point'){add('circle',{cx:g.sx(state.target[0]),cy:g.sy(state.target[1]),r:16,fill:'none',stroke:colors.ghost,'stroke-width':3,'stroke-dasharray':'6 5','pointer-events':'none'});add('circle',{cx:g.sx(state.target[0]),cy:g.sy(state.target[1]),r:4,fill:colors.ghost,'pointer-events':'none'});}
    if(state.mission==='vector'){const T=[state.A[0]+state.target[0],state.A[1]+state.target[1]];add('line',{x1:g.sx(state.A[0]),y1:g.sy(state.A[1]),x2:g.sx(T[0]),y2:g.sy(T[1]),stroke:colors.ghost,'stroke-width':3,'stroke-dasharray':'7 6','marker-end':'url(#posGhost)','pointer-events':'none'});add('text',{x:g.sx(T[0])+10,y:g.sy(T[1])-9,fill:colors.ghost,'font-size':11,'font-weight':800,'pointer-events':'none'},'목표 '+fmt(state.target));}
    add('line',{x1:g.sx(state.A[0]),y1:g.sy(state.A[1]),x2:g.sx(state.B[0]),y2:g.sy(state.A[1]),stroke:colors.A,'stroke-width':2,'stroke-dasharray':'5 5','pointer-events':'none'});add('line',{x1:g.sx(state.B[0]),y1:g.sy(state.A[1]),x2:g.sx(state.B[0]),y2:g.sy(state.B[1]),stroke:colors.B,'stroke-width':2,'stroke-dasharray':'5 5','pointer-events':'none'});add('line',{x1:g.sx(state.A[0]),y1:g.sy(state.A[1]),x2:g.sx(state.B[0]),y2:g.sy(state.B[1]),stroke:colors.vector,'stroke-width':4,'stroke-linecap':'round','marker-end':'url(#posVector)','pointer-events':'none'});
    const free=state.mission==='free';handle(g,state.mode==='position'?'O':'A',state.A,colors.A,free&&state.mode==='displacement');handle(g,state.mode==='position'?'P':'B',state.B,colors.B,true);return v;}
  function math(id,tex){const el=document.getElementById(id);if(window.katex){try{window.katex.render(tex,el,{displayMode:false,throwOnError:false,strict:false});return;}catch(error){console.warn('[Position Lab] 수식을 일반 텍스트로 표시합니다.',error);}}el.textContent=tex;}
  function updateReadouts(v){const start=state.mode==='position'?'O': 'A',end=state.mode==='position'?'P':'B',arrow='\\overrightarrow{'+start+end+'}';math('positionPoints',start+fmt(state.A)+'\\longrightarrow '+end+fmt(state.B));math('positionComponents',arrow+'='+fmt(v));math('positionSubtract',fmt(state.B)+'-'+fmt(state.A)+'='+fmt(v));math('positionMagnitude','|'+arrow+'|=\\sqrt{'+(v[0]*v[0])+'+'+(v[1]*v[1])+'}\\approx '+Math.hypot.apply(null,v).toFixed(2));}
  function updateMission(v){const kicker=brief.querySelector('[data-position-kicker]'),title=brief.querySelector('[data-position-title]'),copy=brief.querySelector('[data-position-copy]'),next=brief.querySelector('[data-position-next]'),meter=brief.querySelector('[data-position-meter]');let success=false,progress=0;next.classList.toggle('hidden',state.mission==='free');if(state.mission==='free'){kicker.textContent='FREE LAB';title.textContent='끝점을 직접 움직여 보세요.';copy.textContent=state.mode==='position'?'점 P의 좌표가 곧 위치벡터 OP의 성분이 됩니다.':'종점 B의 좌표에서 시점 A의 좌표를 빼면 AB의 성분이 됩니다.';}else if(state.mission==='point'){const gap=Math.hypot(state.B[0]-state.target[0],state.B[1]-state.target[1]);success=gap<.01;progress=Math.max(5,100-gap/12*100);kicker.textContent=success?'POINT LOCKED':'POINT HUNT';title.textContent=success?'점 P가 목표 좌표에 도착했습니다!':'점 P를 '+fmt(state.target)+'로 옮기세요.';copy.textContent=success?'P의 좌표와 위치벡터 OP의 성분이 정확히 일치합니다.':'현재 P'+fmt(state.B)+' · 파란 끝점을 목표점까지 끌어 보세요.';}else{const gap=Math.hypot(v[0]-state.target[0],v[1]-state.target[1]);success=gap<.01;progress=Math.max(5,100-gap/12*100);kicker.textContent=success?'COMPONENT LOCKED':'VECTOR TRANSFER';title.textContent=success?'목표 성분 벡터를 만들었습니다!':'AB의 성분을 '+fmt(state.target)+'로 만드세요.';copy.textContent=success?'시점이 달라도 같은 성분이면 길이와 방향이 같은 벡터입니다.':'현재 AB='+fmt(v)+' · A와 B를 움직여 같은 이동량을 만드세요.';}brief.classList.toggle('success',success);svg.classList.toggle('mission-success',success);meter.style.width=progress+'%';}
  function render(){const v=draw();updateReadouts(v);updateMission(v);}
  function reset(){state.trails={A:[],B:[]};if(state.mission==='point'){state.A=[0,0];state.B=[1,2];state.target=pointTargets[state.targetIndex%pointTargets.length].slice();}else if(state.mission==='vector'){state.A=[-2,-1];state.B=[1,-2];state.target=vectorTargets[state.targetIndex%vectorTargets.length].slice();}else if(state.mode==='position'){state.A=[0,0];state.B=[3,2];}else{state.A=[-2,-1];state.B=[3,2];}render();}
  function setMode(mode){if(state.mission!=='free')return;state.mode=mode;chips.querySelectorAll('.chip').forEach(function(b){b.classList.toggle('active',b.dataset.positionMode===mode);});reset();}
  function setMission(name){state.mission=name;state.targetIndex=0;if(name==='point')state.mode='position';if(name==='vector')state.mode='displacement';tabs.querySelectorAll('[data-position-mission]').forEach(function(b){b.classList.toggle('active',b.dataset.positionMission===name);});chips.querySelectorAll('.chip').forEach(function(b){b.classList.toggle('active',b.dataset.positionMode===state.mode);});chips.classList.toggle('mission-locked',name!=='free');reset();}
  chips.querySelectorAll('.chip').forEach(function(b){b.addEventListener('click',function(){setMode(b.dataset.positionMode);});});tabs.querySelectorAll('[data-position-mission]').forEach(function(b){b.addEventListener('click',function(){setMission(b.dataset.positionMission);});});brief.querySelector('[data-position-next]').addEventListener('click',function(){state.targetIndex++;reset();});controls.querySelector('[data-position-reset]').addEventListener('click',reset);
  svg.addEventListener('pointerdown',function(event){const name=event.target.dataset.positionPoint;if(!name)return;if(name==='O')return;if(state.mission==='point'&&name!=='P')return;dragging=name==='A'?'A':'B';svg.setPointerCapture(event.pointerId);svg.classList.add('is-dragging');});svg.addEventListener('pointermove',function(event){if(!dragging)return;const r=svg.getBoundingClientRect(),x=(event.clientX-r.left)/r.width*640,y=(event.clientY-r.top)/r.height*400,g=G.cartesian(svg,{xmin:-6,xmax:6,ymin:-5,ymax:5}),next=[G.clamp(Math.round(g.xOf(x)),-5,5),G.clamp(Math.round(g.yOf(y)),-4,4)];if(next[0]===state[dragging][0]&&next[1]===state[dragging][1])return;state.trails[dragging].push(state[dragging].slice());state.trails[dragging]=state.trails[dragging].slice(-7);state[dragging]=next;render();});function end(){dragging=null;svg.classList.remove('is-dragging');}svg.addEventListener('pointerup',end);svg.addEventListener('pointercancel',end);document.addEventListener('jp:math-ready',render,{once:true});render();
})();
