/* 아이디어 뱅크에서 옮긴 탐구 씨앗 96개.
   출처: "JP Math Lab × 2022 개정 교육과정 콘텐츠 아이디어 뱅크.md"
     · 수학이 필요한 순간 32  (급 S++) — 학생이 수학을 발명할 수밖에 없는 상황
     · S+ 후보 핵심 주제 64   (급 S+)  — 다시 비틀어 만든 질문

   이 파일은 손으로 고치지 않는다. 뱅크 문서를 고치고 다시 뽑는다.
   문서에 없는 값은 넣지 않았다. 비어 있으면 문서에 없는 것이다.
   모두 검증 전이다. */
(function () {
  'use strict';

  window.JPSeedsBank = [
  {"id": "BANK-MOMENT-01", "src": "moment", "grade": "S++", "subject": "calc", "title": "순간을 측정할 수 없는 문제", "question": "사진 한 장에서 속도를 어떻게 알아낼까?", "situation": "자동차가 카메라 앞을 통과한다. 사진 한 장에는 위치만 있다.", "math": "극한 → 미분계수.", "predict": "앞뒤 사진을 사용한다.", "conflict": "그러면 그것은 순간속도가 아니라 평균속도다.", "discovery": "시간 간격을 없애는 것이 아니라, 0에 가까워질 때의 패턴을 본다.", "format": "CINEMA + SIMULATION"},
  {"id": "BANK-MOMENT-02", "src": "moment", "grade": "S++", "subject": "calc", "title": "곡선 위의 방향", "question": "지금 자동차가 바라봐야 하는 정확한 방향은?", "situation": "게임 자동차가 곡선 도로 위를 달린다.", "math": "할선 → 접선 → 미분.", "format": "GAME", "notes": ["두 점으로 방향을 잡고 두 번째 점을 가까이 이동."]},
  {"id": "BANK-MOMENT-03", "src": "moment", "grade": "S++", "subject": "calc", "title": "속도만 남은 자동차", "question": "차가 얼마나 멀리 갔는지 복원할 수 있을까?", "situation": "GPS 기록은 사라지고 속도계 기록만 남았다.", "math": "정적분.", "twist": "그래프 아래 '넓이'가 실제 '거리'가 된다."},
  {"id": "BANK-MOMENT-04", "src": "moment", "grade": "S++", "subject": "geo", "title": "그림자로 3차원을 복원", "question": "그림자 몇 장이면 원래 입체를 추측할 수 있을까?", "situation": "정체불명의 입체가 있고 그림자만 보인다.", "math": "정사영·공간벡터.", "format": "MYSTERY GAME", "notes": ["빛의 방향을 바꾸면 그림자가 달라진다."]},
  {"id": "BANK-MOMENT-05", "src": "moment", "grade": "S++", "subject": "geo", "title": "지붕 위 태양광", "question": "패널 넓이가 같아도 왜 받는 에너지가 달라질까?", "situation": "경사진 지붕에 태양광 패널을 설치한다.", "math": "정사영 + 내적의 직관.", "act": "태양 방향과 지붕 각도."},
  {"id": "BANK-MOMENT-06", "src": "moment", "grade": "S++", "subject": "geo", "title": "보이지 않는 적", "question": "게임은 어떻게 시야 안의 적만 발견할까?", "situation": "게임 캐릭터 뒤에 적이 있다. 거리만으로는 앞/뒤를 구별할 수 없다.", "math": "벡터·내적."},
  {"id": "BANK-MOMENT-07", "src": "moment", "grade": "S++", "subject": "geo", "title": "측풍 착륙", "question": "비행기 기수를 활주로 정면으로 두면 어디에 도착할까?", "situation": "활주로는 정면인데 강한 옆바람이 분다.", "math": "벡터 합.", "notes": ["학생이 직접 조종하고 실패."]},
  {"id": "BANK-MOMENT-08", "src": "moment", "grade": "S++", "subject": "geo", "title": "접시가 신호를 모으는 이유", "question": "모두 같은 수신기로 보내는 모양은?", "situation": "수많은 평행 전파가 접시 위 여러 곳에 닿는다.", "math": "포물선.", "notes": ["학생이 곡률을 바꿔 직접 맞춤."]},
  {"id": "BANK-MOMENT-09", "src": "moment", "grade": "S++", "subject": "geo", "title": "속삭이는 방", "question": "왜 특정 위치에서만 또렷하게 들릴까?", "situation": "두 학생이 멀리 떨어져 벽을 보고 속삭인다.", "math": "타원의 초점."},
  {"id": "BANK-MOMENT-10", "src": "moment", "grade": "S++", "subject": "geo", "title": "신호의 출발지를 찾아라", "question": "방향을 몰라도 발신지를 찾을 수 있을까?", "situation": "세 수신기에 신호가 서로 다른 시각에 도착한다.", "math": "쌍곡선/거리차."},
  {"id": "BANK-MOMENT-11", "src": "moment", "grade": "S++", "subject": "algebra", "title": "42번의 종이", "situation": "학생에게 먼저 선택시킨다. - 교실 천장 - 에베레스트 - 우주정거장 - 달 그 후 지수성장을 재생.", "notes": ["결과를 알려주는 것이 아니라 예측을 기록한 뒤 깨뜨린다."]},
  {"id": "BANK-MOMENT-12", "src": "moment", "grade": "S++", "subject": "algebra", "title": "바이럴 버튼", "question": "0.1명 차이가 정말 중요할까?", "situation": "한 사람이 평균 1.0명, 1.1명, 1.5명에게 공유한다.", "math": "등비·지수.", "notes": ["시간을 빠르게 돌리면 세계가 갈린다."]},
  {"id": "BANK-MOMENT-13", "src": "moment", "grade": "S++", "subject": "algebra", "title": "로그를 직접 발명하게 하기", "question": "이 표가 있다면 계산 세계가 어떻게 바뀔까?", "situation": "학생에게 거대한 곱셈 20개를 제한시간 안에 준다.", "math": "로그의 탄생 이유.", "notes": ["곱셈을 덧셈으로 바꿀 수 있는 표를 발견."]},
  {"id": "BANK-MOMENT-14", "src": "moment", "grade": "S++", "subject": "econ", "title": "50%의 함정", "situation": "100,000원 상품. 50% 할인 → 50% 인상. 학생에게 \"원래 가격?\" YES/NO를 먼저 누르게 한다.", "math": "기준량·비율."},
  {"id": "BANK-MOMENT-15", "src": "moment", "grade": "S++", "subject": "algebra", "title": "복리 타임머신", "question": "돈보다 시간이 더 강력한 변수가 될 수 있을까?", "situation": "학생이 월 저축액보다 시작 시점을 조작한다. 20세/30세/40세 시작을 비교.", "math": "지수·등비수열·현재/미래가치."},
  {"id": "BANK-MOMENT-16", "src": "moment", "grade": "S++", "subject": "algebra", "title": "대출 상환 레이스", "situation": "같은 원금·금리에서 상환 구조만 바꾼다. 매달 남은 원금이 3D 블록처럼 깎인다.", "math": "수열·금융수학."},
  {"id": "BANK-MOMENT-17", "src": "moment", "grade": "S++", "subject": "prob", "title": "생일 버튼", "situation": "우리 반에서 생일이 겹칠 확률은 몇 %? 학생이 5/20/50/80% 중 선택. 사람을 한 명씩 방에 넣는다.", "math": "여사건."},
  {"id": "BANK-MOMENT-18", "src": "moment", "grade": "S++", "subject": "prob", "title": "몬티홀 실제 게임", "situation": "설명 금지. 먼저 10번 플레이. '유지'와 '변경' 승률을 학생 자신의 데이터로 보여준다. 그 후 전체 시뮬레이션 10,000회.", "math": "조건부확률."},
  {"id": "BANK-MOMENT-19", "src": "moment", "grade": "S++", "subject": "prob", "title": "99% 정확한 검사", "question": "같은 99% 검사인데 양성의 의미가 왜 달라질까?", "situation": "학생에게 10,000명의 사람 점을 보여준다. 질병 유병률을 슬라이더로 조절.", "math": "조건부확률·기저율."},
  {"id": "BANK-MOMENT-20", "src": "moment", "grade": "S++", "subject": "prob", "title": "여론조사 전쟁", "situation": "A: 자발적 온라인 투표 100,000명 B: 무작위 표본 1,000명 어느 쪽을 믿을 것인가?\" 먼저 선택. 실제 모집단을 공개하고 반복 샘플링.", "math": "표본·편향."},
  {"id": "BANK-MOMENT-21", "src": "moment", "grade": "S++", "subject": "prob", "title": "평균연봉 회사", "situation": "직원 9명의 연봉은 그대로. CEO 연봉만 폭증. 우리 회사 평균연봉 40% 상승!\" 광고 등장.", "math": "평균·중앙값·분포."},
  {"id": "BANK-MOMENT-22", "src": "moment", "grade": "S++", "subject": "prob", "title": "총알 자국", "situation": "돌아온 비행기의 총알 구멍을 학생이 직접 클릭해 장갑을 보강한다. 그 선택대로 다음 비행을 시뮬레이션.", "math": "선택편향.", "twist": "구멍 없는 부분이 치명적이었다."},
  {"id": "BANK-MOMENT-23", "src": "moment", "grade": "S++", "subject": "common", "title": "GPS 미스터리", "situation": "지도에 플레이어 위치를 숨긴다. 기지국 하나의 거리 → 원 하나. 두 개 → 두 후보. 세 개 → 한 위치.", "math": "원의 방정식·교점."},
  {"id": "BANK-MOMENT-24", "src": "moment", "grade": "S++", "subject": "common", "title": "검은 백조", "situation": "화면에 흰 백조가 계속 등장한다. 10 → 100 → 10,000마리. \"모든 백조는 희다\" 버튼이 점점 유혹적이 된다. 마지막에 검은 백조 한 마리.", "math": "명제·반례."},
  {"id": "BANK-MOMENT-25", "src": "moment", "grade": "S++", "subject": "ai", "title": "비밀번호 우주", "situation": "4자리 → 6자리 → 8자리. 모든 후보가 실제 공간의 문처럼 복제되어 카메라가 뒤로 빠진다.", "math": "곱의 법칙·경우의 수."},
  {"id": "BANK-MOMENT-26", "src": "moment", "grade": "S++", "subject": "ai", "title": "AI의 단어 지도", "question": "컴퓨터에게 의미를 거리로 만들 수 있을까?", "situation": "'고양이, 강아지, 자동차, 버스...'가 공간의 점으로 나타난다. 비슷한 단어가 군집.", "math": "벡터·거리·유사도."},
  {"id": "BANK-MOMENT-27", "src": "moment", "grade": "S++", "subject": "ai", "title": "AI 산 내려가기", "situation": "학생이 학습률을 선택. 너무 작음 → 느림. 너무 큼 → 골짜기를 튕겨나감. 적당함 → 최솟값 도착.", "math": "미분·기울기·최적화."},
  {"id": "BANK-MOMENT-28", "src": "moment", "grade": "S++", "subject": "ai", "title": "과적합 드로잉", "question": "100점짜리 모델이 왜 더 못할까?", "situation": "점 두 무리가 있다. 학생이 분류 경계를 직접 그린다. 훈련점 하나하나를 완벽하게 피해가는 괴상한 선 vs 단순한 선. 새 데이터 공개."},
  {"id": "BANK-MOMENT-29", "src": "moment", "grade": "S++", "subject": "ai", "title": "내비게이션 탐색", "situation": "지도 전체 경로를 보여주지 않는다. 알고리즘이 교차로를 하나씩 탐색하는 모습을 파동처럼 보여준다. 학생은 탐색 전략을 선택.", "math": "그래프·최단경로."},
  {"id": "BANK-MOMENT-30", "src": "moment", "grade": "S++", "subject": "ai", "title": "쾨니히스베르크", "situation": "처음에는 실제 도시처럼 보여준다. 학생이 직접 다리를 걷는다. 실패 반복. 그 후 건물·강·거리 모두 사라지고 점과 선만 남는다. 문제에 필요 없는 것을 버렸더니 새로운 수학이 태어났다.", "math": "그래프이론."},
  {"id": "BANK-MOMENT-31", "src": "moment", "grade": "S++", "subject": "culture", "title": "원근법 해킹", "situation": "학생에게 평면 화면에 두 개의 같은 크기 사람을 놓게 한다. 소실점과 투영선을 켜는 순간 뒤쪽 사람이 '커야' 같은 크기로 보이는 이유 발견.", "math": "투영·닮음·비례."},
  {"id": "BANK-MOMENT-32", "src": "moment", "grade": "S++", "subject": "algebra", "title": "음계의 비밀", "situation": "건반을 '주파수 간격이 같은 자' 위에 놓으면 음계가 이상하게 벌어진다. 로그 축으로 바꾸면 옥타브가 규칙적으로 정렬된다.", "math": "지수·로그·비율."},
  {"id": "BANK-SPLUS-01", "src": "splus", "grade": "S+", "subject": "calc", "category": "극한·미분·적분", "title": "극한 · 제논보다 더 직접적으로", "question": "목표까지 남은 거리의 절반씩만 간다면, 영원히 도착하지 못할까?", "scene": "복도 끝 문까지 절반 → 절반 → 절반. 카메라는 실제로 문에 도착한다.", "lab": "분할 비율을 학생이 바꾸고 총 이동거리 관찰.", "notes": ["반전: 무한히 많은 과정과 유한한 결과가 동시에 가능하다."]},
  {"id": "BANK-SPLUS-02", "src": "splus", "grade": "S+", "subject": "calc", "category": "극한·미분·적분", "title": "극한 · 픽셀", "question": "화면을 계속 확대하면 원은 언제부터 원이 아니게 될까?", "scene": "매끈한 원 → 확대 → 계단 모양 픽셀.", "lab": "해상도와 확대율 조절.", "notes": ["연결: 연속적인 수학과 이산적인 디지털 세계."]},
  {"id": "BANK-SPLUS-03", "src": "splus", "grade": "S+", "subject": "calc", "category": "극한·미분·적분", "title": "미분 · 순간속도", "question": "속도계는 1초 뒤를 보지 않고 어떻게 지금 속도를 알까?", "scene": "자동차 → 시간창 1초/0.1초/0.01초 → 접선.", "lab": "시간 간격을 직접 0에 접근."},
  {"id": "BANK-SPLUS-04", "src": "splus", "grade": "S+", "subject": "calc", "category": "극한·미분·적분", "title": "미분 · 확대", "question": "곡선은 가까이서 보면 정말 직선일까?", "scene": "거대한 곡면 위 카메라 → 끝없는 줌 → 직선처럼 변함.", "notes": ["연결: 국소 선형성."]},
  {"id": "BANK-SPLUS-05", "src": "splus", "grade": "S+", "subject": "calc", "category": "극한·미분·적분", "title": "미분 · 롤러코스터", "question": "롤러코스터 꼭대기에서 딱 한순간, 기울기는 어디로 사라질까?", "scene": "1인칭 트랙 → 정상에서 정지한 듯한 순간 → 접선 수평.", "lab": "트랙 제어점 이동, 극값 변화."},
  {"id": "BANK-SPLUS-06", "src": "splus", "grade": "S+", "subject": "calc", "category": "극한·미분·적분", "title": "미분 · 최적화", "question": "피자 상자를 만들 때 종이를 가장 적게 쓰는 모양은?", "scene": "같은 부피의 상자들이 형태를 바꾸며 표면적 숫자 변화.", "lab": "치수 드래그로 최소값 찾기."},
  {"id": "BANK-SPLUS-07", "src": "splus", "grade": "S+", "subject": "calc", "category": "극한·미분·적분", "title": "적분 · 아르키메데스", "question": "적분도 π도 없던 시대에 원을 어떻게 계산했을까?", "scene": "양피지 → 6 → 12 → 24 → 48 → 96각형 → 가장자리 초근접.", "lab": "다각형 변 수 증가와 오차 확인."},
  {"id": "BANK-SPLUS-08", "src": "splus", "grade": "S+", "subject": "calc", "category": "극한·미분·적분", "title": "적분 · 속도계", "question": "자동차의 속도 기록만 남아 있다면, 어디까지 갔는지 복원할 수 있을까?", "scene": "속도 그래프 아래 면적이 실제 도로 거리로 변환."},
  {"id": "BANK-SPLUS-09", "src": "splus", "grade": "S+", "subject": "calc", "category": "극한·미분·적분", "title": "기본정리", "question": "기울기를 재는 미분과 넓이를 재는 적분이 왜 서로 취소될까?", "scene": "곡선 아래 물이 차오름 → 누적 높이 그래프 → 그 그래프의 기울기와 원래 함수가 포개짐."},
  {"id": "BANK-SPLUS-10", "src": "splus", "grade": "S+", "subject": "algebra", "category": "지수·로그·수열", "title": "지수 · 종이", "question": "종이를 42번 접으면 달에 닿는다. 계산은 맞다. 그런데 왜 불가능할까?", "notes": ["수학과 물리적 현실의 차이까지 다룬다."]},
  {"id": "BANK-SPLUS-11", "src": "splus", "grade": "S+", "subject": "algebra", "category": "지수·로그·수열", "title": "지수 · 감염", "question": "처음 10명일 때는 아무도 신경 쓰지 않았다.", "scene": "지도에 점 10개 → 20 → 40 → 도시 전체.", "notes": ["핵심: 지수성장은 초반에 직관을 속인다."]},
  {"id": "BANK-SPLUS-12", "src": "splus", "grade": "S+", "subject": "algebra", "category": "지수·로그·수열", "title": "로그 · 별", "question": "별의 밝기는 왜 그냥 숫자로 쓰지 않고 등급으로 말할까?", "notes": ["엄청난 크기 범위를 압축하는 로그."]},
  {"id": "BANK-SPLUS-13", "src": "splus", "grade": "S+", "subject": "algebra", "category": "지수·로그·수열", "title": "로그 · 계산 혁명", "question": "계산기 하나 없던 천문학자가 8자리 곱셈을 수천 번 해야 했다.", "notes": ["곱셈 → 로그표 → 덧셈 → 역로그."]},
  {"id": "BANK-SPLUS-14", "src": "splus", "grade": "S+", "subject": "algebra", "category": "지수·로그·수열", "title": "로그 · 데시벨", "question": "소리가 10dB 커졌다는 건 10만큼 커졌다는 뜻이 아니다.", "notes": ["소리 파동과 로그척도."]},
  {"id": "BANK-SPLUS-15", "src": "splus", "grade": "S+", "subject": "algebra", "category": "지수·로그·수열", "title": "등비수열 · 조회수", "question": "조회수 100짜리 영상이 어느 순간 100만이 되는 과정은 선형이 아니다.", "notes": ["공유 한 명이 몇 명에게 전달하는지에 따른 확산."]},
  {"id": "BANK-SPLUS-16", "src": "splus", "grade": "S+", "subject": "algebra", "category": "지수·로그·수열", "title": "귀납법", "question": "무한히 많은 도미노를 직접 확인하지 않고 전부 쓰러진다고 어떻게 증명할까?"},
  {"id": "BANK-SPLUS-17", "src": "splus", "grade": "S+", "subject": "geo", "category": "기하·벡터·공간", "title": "포물선 · 안테나", "question": "하늘 어디서 온 전파든 왜 접시 한 점으로 모일까?", "notes": ["평행선 → 반사 → 초점."]},
  {"id": "BANK-SPLUS-18", "src": "splus", "grade": "S+", "subject": "geo", "category": "기하·벡터·공간", "title": "포물선 · 자동차 헤드라이트", "question": "전구 하나의 빛을 어떻게 거의 평행하게 앞으로 보낼까?", "notes": ["안테나와 정확히 반대 방향의 포물선 반사."]},
  {"id": "BANK-SPLUS-19", "src": "splus", "grade": "S+", "subject": "geo", "category": "기하·벡터·공간", "title": "타원 · 속삭이는 방", "question": "수십 미터 떨어진 사람의 속삭임이 바로 귀 옆에서 들린다면?", "notes": ["두 초점."]},
  {"id": "BANK-SPLUS-20", "src": "splus", "grade": "S+", "subject": "geo", "category": "기하·벡터·공간", "title": "타원 · 행성", "question": "왜 행성은 태양을 중심으로 완벽한 원을 그리지 않을까?", "notes": ["케플러와 타원."]},
  {"id": "BANK-SPLUS-21", "src": "splus", "grade": "S+", "subject": "geo", "category": "기하·벡터·공간", "title": "쌍곡선 · 위치추적", "question": "신호가 어디서 왔는지 방향을 몰라도 도착 시간 차이만 알면 찾을 수 있다."},
  {"id": "BANK-SPLUS-22", "src": "splus", "grade": "S+", "subject": "geo", "category": "기하·벡터·공간", "title": "원뿔곡선", "question": "원을 비스듬히 자르기 시작했을 뿐인데 네 종류의 곡선이 태어났다.", "notes": ["3D 원뿔을 카메라가 돌며 절단."]},
  {"id": "BANK-SPLUS-23", "src": "splus", "grade": "S+", "subject": "geo", "category": "기하·벡터·공간", "title": "벡터 · 강 건너기", "question": "목적지를 향해 똑바로 노를 저으면 목적지에 도착하지 못한다."},
  {"id": "BANK-SPLUS-24", "src": "splus", "grade": "S+", "subject": "geo", "category": "기하·벡터·공간", "title": "벡터 · 비행기", "question": "비행기는 옆을 보고 날면서도 직진할 수 있다.", "notes": ["측풍 + 기수 방향 + 실제 이동 방향."]},
  {"id": "BANK-SPLUS-25", "src": "splus", "grade": "S+", "subject": "geo", "category": "기하·벡터·공간", "title": "내적 · 게임 AI", "question": "적이 내 앞에 있는지 게임은 눈도 없이 어떻게 알까?", "notes": ["캐릭터 시선 벡터와 적 방향 벡터."]},
  {"id": "BANK-SPLUS-26", "src": "splus", "grade": "S+", "subject": "geo", "category": "기하·벡터·공간", "title": "내적 · 조명", "question": "게임 속 벽은 빛을 정면으로 받을수록 왜 밝아질까?", "notes": ["법선 벡터와 빛 벡터의 내적."]},
  {"id": "BANK-SPLUS-27", "src": "splus", "grade": "S+", "subject": "geo", "category": "기하·벡터·공간", "title": "정사영 · 지붕", "question": "3차원 지붕을 도면 한 장에 정확히 눌러 담을 수 있을까?", "notes": ["실제 지붕 → 빛 → 투영 → 평면도."]},
  {"id": "BANK-SPLUS-28", "src": "splus", "grade": "S+", "subject": "geo", "category": "기하·벡터·공간", "title": "정사영 · 그림자", "question": "같은 물체의 그림자가 길어졌다 짧아졌다 하는 건 무엇이 바뀐 걸까?", "notes": ["태양 벡터와 투영."]},
  {"id": "BANK-SPLUS-29", "src": "splus", "grade": "S+", "subject": "geo", "category": "기하·벡터·공간", "title": "공간좌표 · 드론", "question": "드론에게 '오른쪽으로 가'라고 말하는 것만으로 부족한 이유는?", "notes": ["3축 위치와 방향."]},
  {"id": "BANK-SPLUS-30", "src": "splus", "grade": "S+", "subject": "geo", "category": "기하·벡터·공간", "title": "평면 · 충돌", "question": "총알이 벽을 뚫었는지 게임은 매 프레임 어떻게 계산할까?", "notes": ["직선과 평면의 교점."]},
  {"id": "BANK-SPLUS-31", "src": "splus", "grade": "S+", "subject": "prob", "category": "확률·통계", "title": "생일 문제", "question": "23명만 모여도 생일이 같은 두 사람이 있을 확률이 절반을 넘는다?", "notes": ["사람 아이콘이 하나씩 들어오며 확률 상승."]},
  {"id": "BANK-SPLUS-32", "src": "splus", "grade": "S+", "subject": "prob", "category": "확률·통계", "title": "도박사의 오류", "question": "앞면이 10번 연속 나왔다. 이제 뒷면에 걸어야 할까?"},
  {"id": "BANK-SPLUS-33", "src": "splus", "grade": "S+", "subject": "prob", "category": "확률·통계", "title": "조건부확률", "question": "정확도 99% 검사에서 양성이 나왔다. 정말 99% 확률로 맞을까?", "notes": ["기저율을 점 1,000개로 시각화."]},
  {"id": "BANK-SPLUS-34", "src": "splus", "grade": "S+", "subject": "prob", "category": "확률·통계", "title": "몬티홀", "question": "문 하나를 열어 보여줬는데, 왜 선택을 바꾸는 게 유리할까?", "notes": ["게임쇼 연출."]},
  {"id": "BANK-SPLUS-35", "src": "splus", "grade": "S+", "subject": "prob", "category": "확률·통계", "title": "정규분포", "question": "서로 상관없어 보이는 수많은 측정값이 왜 자꾸 같은 종 모양이 될까?", "notes": ["작은 오차들이 합쳐지는 장면."]},
  {"id": "BANK-SPLUS-36", "src": "splus", "grade": "S+", "subject": "prob", "category": "확률·통계", "title": "표본", "question": "1,000명에게 잘 물으면 5,000만 명의 생각을 알 수 있을까?"},
  {"id": "BANK-SPLUS-37", "src": "splus", "grade": "S+", "subject": "prob", "category": "확률·통계", "title": "표본편향", "question": "10만 명이 참여한 투표가 1,000명 조사보다 틀릴 수 있다.", "notes": ["숫자의 크기보다 뽑는 방식."]},
  {"id": "BANK-SPLUS-38", "src": "splus", "grade": "S+", "subject": "prob", "category": "확률·통계", "title": "상관·인과", "question": "아이스크림이 많이 팔릴수록 익사 사고가 늘어난다. 아이스크림을 금지해야 할까?", "notes": ["숨은 변수 '기온' 등장."]},
  {"id": "BANK-SPLUS-39", "src": "splus", "grade": "S+", "subject": "prob", "category": "확률·통계", "title": "평균의 함정", "question": "회사 평균연봉이 크게 올랐는데 직원 대부분은 한 푼도 더 못 받았다.", "notes": ["한 명의 극단값."]},
  {"id": "BANK-SPLUS-40", "src": "splus", "grade": "S+", "subject": "prob", "category": "확률·통계", "title": "생존자편향", "question": "총알 자국이 많은 곳을 보강하면 비행기가 더 위험해진다?", "notes": ["돌아온 비행기와 돌아오지 못한 비행기."]},
  {"id": "BANK-SPLUS-41", "src": "splus", "grade": "S+", "subject": "common", "category": "공통수학·논리·대수", "title": "복소수", "question": "존재하지 않는 수를 만들었더니 현실의 전기와 파동을 더 쉽게 계산하게 됐다.", "notes": ["수직선이 복소평면으로 열리는 장면."]},
  {"id": "BANK-SPLUS-42", "src": "splus", "grade": "S+", "subject": "common", "category": "공통수학·논리·대수", "title": "이차함수", "question": "농구공·분수·대포알은 왜 비슷한 곡선을 그릴까?", "notes": ["세 장면의 궤적이 하나의 포물선으로 포개짐."]},
  {"id": "BANK-SPLUS-43", "src": "splus", "grade": "S+", "subject": "common", "category": "공통수학·논리·대수", "title": "원의 방정식 · GPS", "question": "위성 하나는 내 위치를 모른다. 여러 개가 만나면 안다.", "notes": ["거리 구/원의 교차."]},
  {"id": "BANK-SPLUS-44", "src": "splus", "grade": "S+", "subject": "common", "category": "공통수학·논리·대수", "title": "명제 · 반례", "question": "백조를 100만 마리 봐도 '모든 백조는 희다'를 증명할 수 없다. 그런데 검은 백조 한 마리면 끝난다."},
  {"id": "BANK-SPLUS-45", "src": "splus", "grade": "S+", "subject": "common", "category": "공통수학·논리·대수", "title": "필요충분조건", "question": "도로가 젖어 있다. 비가 왔다고 결론 내려도 될까?", "notes": ["스프링클러라는 반례 등장."]},
  {"id": "BANK-SPLUS-46", "src": "splus", "grade": "S+", "subject": "common", "category": "공통수학·논리·대수", "title": "행렬", "question": "사진을 숫자표로 바꾸면 회전·확대·AI 인식까지 가능해진다.", "notes": ["실제 사진 → 격자 → 숫자 → 변환."]},
  {"id": "BANK-SPLUS-47", "src": "splus", "grade": "S+", "subject": "common", "category": "공통수학·논리·대수", "title": "경우의 수", "question": "비밀번호 한 자리만 늘렸는데 해킹 시간이 왜 10배가 될까?", "notes": ["조합 폭발."]},
  {"id": "BANK-SPLUS-48", "src": "splus", "grade": "S+", "subject": "common", "category": "공통수학·논리·대수", "title": "함수", "question": "세상을 '입력 하나를 넣으면 무엇이 나오는가'로 보면 갑자기 같은 구조가 보인다.", "notes": ["자판기·환율·온도변환·게임 데미지가 하나의 함수 머신으로."]},
  {"id": "BANK-SPLUS-49", "src": "splus", "grade": "S+", "subject": "econ", "category": "경제수학", "title": "복리", "question": "연 7%라는 작은 숫자가 30년 뒤에는 왜 이렇게 무서울까?", "notes": ["시간축에서 두 자산이 갈라짐."]},
  {"id": "BANK-SPLUS-50", "src": "splus", "grade": "S+", "subject": "econ", "category": "경제수학", "title": "현재가치", "question": "지금 1억과 30년 뒤 1억 중 어느 쪽이 더 큰 돈일까?", "notes": ["돈이 시간축을 이동하며 가치 변화."]},
  {"id": "BANK-SPLUS-51", "src": "splus", "grade": "S+", "subject": "econ", "category": "경제수학", "title": "할인", "question": "50% 할인한 뒤 50% 올리면 왜 원래 가격이 아니지?", "notes": ["같은 50이라는 숫자가 다른 기준값에 적용."]},
  {"id": "BANK-SPLUS-52", "src": "splus", "grade": "S+", "subject": "econ", "category": "경제수학", "title": "대출", "question": "같은 3억을 빌렸는데 누구는 이자를 수천만 원 더 낸다.", "notes": ["상환 방식별 현금흐름."]},
  {"id": "BANK-SPLUS-53", "src": "splus", "grade": "S+", "subject": "econ", "category": "경제수학", "title": "손익분기점", "question": "잘 팔리는데도 망하는 가게가 있다.", "notes": ["매출과 이익은 같은 것이 아님."]},
  {"id": "BANK-SPLUS-54", "src": "splus", "grade": "S+", "subject": "econ", "category": "경제수학", "title": "탄력성", "question": "가격을 올렸는데 매출이 오르는 상품과 떨어지는 상품의 차이는?"},
  {"id": "BANK-SPLUS-55", "src": "splus", "grade": "S+", "subject": "ai", "category": "AI·컴퓨터·이산수학", "title": "AI와 벡터", "question": "AI에게 '왕-남자+여자' 같은 계산이 가능하다는 건 무슨 뜻일까?", "notes": ["단어가 공간의 점/벡터가 되는 장면.", "실제 모델의 동작을 과장해 단정하지 않고 '임베딩 공간의 직관'으로 설명."]},
  {"id": "BANK-SPLUS-56", "src": "splus", "grade": "S+", "subject": "ai", "category": "AI·컴퓨터·이산수학", "title": "경사하강", "question": "AI는 정답 위치를 모르는데 어떻게 산 아래로 내려갈까?", "notes": ["손실 지형과 기울기."]},
  {"id": "BANK-SPLUS-57", "src": "splus", "grade": "S+", "subject": "ai", "category": "AI·컴퓨터·이산수학", "title": "과적합", "question": "100점을 맞았는데 처음 보는 문제는 하나도 못 푼다면?", "notes": ["학생 비유 → AI의 훈련/검증 데이터."]},
  {"id": "BANK-SPLUS-58", "src": "splus", "grade": "S+", "subject": "ai", "category": "AI·컴퓨터·이산수학", "title": "그래프이론", "question": "지하철 노선도는 지리를 틀리게 그렸는데 왜 더 유용할까?", "notes": ["공간의 정확성보다 연결 구조."]},
  {"id": "BANK-SPLUS-59", "src": "splus", "grade": "S+", "subject": "ai", "category": "AI·컴퓨터·이산수학", "title": "최단경로", "question": "내비게이션은 모든 길을 직접 가보지 않고 어떻게 최단길을 찾을까?", "notes": ["탐색 파동이 도로망을 퍼짐."]},
  {"id": "BANK-SPLUS-60", "src": "splus", "grade": "S+", "subject": "ai", "category": "AI·컴퓨터·이산수학", "title": "오일러", "question": "도시의 모든 다리를 딱 한 번씩만 건널 수 있을까?", "notes": ["실제 지도 → 점과 선만 남음 → 그래프이론 탄생."]},
  {"id": "BANK-SPLUS-61", "src": "splus", "grade": "S+", "subject": "ai", "category": "AI·컴퓨터·이산수학", "title": "암호", "question": "비밀 열쇠를 상대에게 보내지 않고도 둘만 같은 비밀을 가질 수 있을까?", "notes": ["공개 정보와 비밀 정보의 분리."]},
  {"id": "BANK-SPLUS-62", "src": "splus", "grade": "S+", "subject": "ai", "category": "AI·컴퓨터·이산수학", "title": "스케줄링", "question": "학교 시간표는 왜 컴퓨터에게도 생각보다 어려운 문제일까?", "notes": ["교사·교실·과목 제약이 겹치며 조합 폭발."]},
  {"id": "BANK-SPLUS-63", "src": "splus", "grade": "S+", "subject": "culture", "category": "수학과 문화·시각", "title": "원근법", "question": "평평한 그림 한 장이 뇌에게 '깊다'고 거짓말하는 방법.", "notes": ["르네상스 거리 → 소실점과 투영선 노출."]},
  {"id": "BANK-SPLUS-64", "src": "splus", "grade": "S+", "subject": "culture", "category": "수학과 문화·시각", "title": "음악과 로그", "question": "한 옥타브 올라갔는데 왜 주파수는 '더하기'가 아니라 두 배가 될까?", "notes": ["건반이 주파수 축과 겹쳐지고 로그 간격으로 정렬."]}
  ];
}());
