const topics = {
  indicator:{n:'01',chapter:'Ⅰ. 수와 경제',color:'#d4673a',code:'ECONOMIC INDICATOR',title:'경제지표',lede:'경제의 상태를 숫자로 요약한 지표를 읽고, 퍼센트와 퍼센트포인트를 정확하게 구분합니다.',terms:[['경제지표','복잡한 경제 상황을 한눈에 비교하려고 만든 대표 숫자예요.','성적표의 평균처럼 물가·실업·성장 상태를 요약해요.'],['퍼센트포인트','두 퍼센트 값 사이의 단순한 차이예요.','금리 4%→6%는 2%포인트 상승이에요.']],principle:'차이와 변화율은 기준이 달라요',copy:'퍼센트 값끼리 빼면 퍼센트포인트, 처음 값과 비교하려면 차이를 처음 값으로 나눕니다.',formula:'차이 = 새 값 − 이전 값<br>변화율 = 차이 ÷ 이전 값 × 100',example:'4%에서 6%가 되면 차이는 2%p이고, 이전 4%에 비해서는 50% 상승한 것입니다.',warning:'“2% 상승”이라고만 쓰면 단순한 차이인지 변화율인지 모호합니다. 경제 기사에서는 %와 %p를 구분해야 합니다.',lab:'indicator',quiz:['금리가 4%에서 6%가 되었다. 가장 정확한 표현은?',['2% 상승했다.','2%포인트, 처음보다 50% 상승했다.','처음보다 150% 상승했다.'],1,'6−4=2%포인트이고, 2÷4×100=50%입니다.']},
  exchange:{n:'02',chapter:'Ⅰ. 수와 경제',color:'#d4673a',code:'EXCHANGE RATE',title:'환율',lede:'서로 다른 나라의 돈을 바꾸는 비율을 계산하고 환율 변화의 의미를 생활 속 가격과 연결합니다.',terms:[['환율','한 나라 돈을 다른 나라 돈으로 바꾸는 교환 비율이에요.','1달러=1,400원이라면 1달러를 사는 데 1,400원이 필요해요.'],['원화 가치','원화 한 단위로 살 수 있는 외국 돈의 양이에요.','원/달러 환율이 오르면 같은 달러를 사는 데 원화가 더 들어요.']],principle:'통화의 단위를 보고 곱할지 나눌지 결정해요',copy:'원/달러 환율은 “1달러당 몇 원”이라는 뜻입니다. 달러를 원화로 바꿀 때는 달러 금액에 환율을 곱합니다.',formula:'필요한 원화 = 달러 × 원/달러 환율',example:'100달러를 1달러당 1,380원에 바꾸면 100×1,380=138,000원이 필요합니다.',warning:'원/달러 환율 상승은 달러 가치 상승이자 원화 가치 하락을 뜻합니다. 숫자가 올랐다고 원화가 강해진 것은 아닙니다.',lab:'exchange',quiz:['같은 100달러를 살 때 환율이 1,300원에서 1,400원으로 오르면?',['필요한 원화가 10,000원 늘어난다.','필요한 원화가 10,000원 줄어든다.','필요한 원화는 변하지 않는다.'],0,'100×(1,400−1,300)=10,000원이 더 필요합니다.']},
  tax:{n:'03',chapter:'Ⅰ. 수와 경제',color:'#d4673a',code:'TAX',title:'세금',lede:'세율을 소수로 바꾸어 세금과 세후 금액을 계산하고 세금이 가격에 미치는 영향을 살펴봅니다.',terms:[['세금','공공서비스에 필요한 돈을 마련하기 위해 국가나 지방자치단체에 내는 돈이에요.','도로·학교·소방 같은 공동 서비스를 운영하는 재원이 돼요.'],['세율','과세 대상 금액 중 세금으로 내는 비율이에요.','세율 10%는 금액 100원당 10원이라는 뜻이에요.']],principle:'퍼센트를 소수로 바꾸어 곱해요',copy:'세율 10%는 0.1입니다. 과세 전 금액에 세율을 곱하면 세금, 둘을 더하면 세후 금액입니다.',formula:'세금 = 과세 전 금액 × 세율<br>세후 금액 = 과세 전 금액 + 세금',example:'8,000원의 10%는 800원이고 세후 금액은 8,800원입니다.',warning:'10%를 그대로 10으로 곱하지 않습니다. 10%=10÷100=0.1로 바꾸어 계산합니다.',lab:'tax',quiz:['공급가액 15,000원에 세율 10%를 적용한 세후 금액은?',['15,150원','16,500원','25,000원'],1,'세금은 15,000×0.1=1,500원, 세후 금액은 16,500원입니다.']},
  sequence:{n:'04',chapter:'Ⅰ. 수와 경제',color:'#d4673a',code:'SEQUENCE',title:'수열',lede:'일정하게 늘거나 일정한 비율로 늘어나는 경제 자료를 수열로 표현합니다.',terms:[['수열','일정한 순서와 규칙에 따라 나열한 수의 모임이에요.','매달 1만 원씩 늘어나는 저축액을 차례로 적을 수 있어요.'],['공차·공비','각 항이 더해지는 일정한 값, 또는 곱해지는 일정한 비율이에요.','10, 15, 20의 공차는 5이고 10, 20, 40의 공비는 2예요.']],principle:'같은 차이는 등차, 같은 비율은 등비예요',copy:'등차수열은 일정한 금액이 더해지고, 등비수열은 이전 항에 일정한 배수가 곱해집니다.',formula:'등차: aₙ = a₁+(n−1)d<br>등비: aₙ = a₁rⁿ⁻¹',example:'첫 달 10만 원에서 매달 2만 원씩 늘면 6개월째 금액은 10+5×2=20만 원입니다.',warning:'“매달 5만 원 증가”와 “매달 5% 증가”는 전혀 다릅니다. 앞은 등차, 뒤는 등비입니다.',lab:'sequence',quiz:['첫 달 20만 원, 매달 3만 원씩 늘어날 때 5개월째 금액은?',['29만 원','32만 원','35만 원'],1,'20+(5−1)×3=32만 원입니다.']},
  finance:{n:'05',chapter:'Ⅰ. 수와 경제',color:'#d4673a',code:'SEQUENCE & FINANCE',title:'수열과 금융',lede:'단리와 복리를 비교하고, 미래의 돈을 오늘의 가치로 바꾸어 봅니다.',terms:[['단리','처음 맡긴 원금에만 이자가 붙는 방식이에요.','원금 100만 원, 5%라면 해마다 5만 원씩 늘어요.'],['복리','원금뿐 아니라 앞서 생긴 이자에도 다시 이자가 붙는 방식이에요.','눈덩이처럼 시간이 길수록 단리와 차이가 커져요.'],['현재가치','미래에 받을 돈을 오늘 시점의 가치로 바꾼 금액이에요.','1년 뒤 105만 원과 오늘 100만 원을 같은 기준에서 비교해요.']],principle:'복리는 등비수열로 커져요',copy:'이자율이 r이고 기간이 n일 때 복리 원리합계는 매 기간 (1+r)배가 됩니다.',formula:'복리 미래가치 = 원금 × (1+r)ⁿ<br>현재가치 = 미래금액 ÷ (1+r)ⁿ',example:'100만 원을 연 5% 복리로 3년 두면 약 115만 7,625원이 됩니다.',warning:'연 이자율과 월 이자율, 기간의 단위를 맞춰야 합니다. 연 6%를 무조건 월 6%로 계산하면 안 됩니다.',lab:'finance',quiz:['같은 원금·양의 이자율·3년 조건에서 일반적으로 더 큰 금액은?',['단리 원리합계','복리 원리합계','항상 같다'],1,'복리는 앞서 생긴 이자에도 이자가 붙으므로 2년 이후부터 단리보다 커집니다.']},
  cost:{n:'06',chapter:'Ⅱ. 함수와 경제',color:'#287d8e',code:'PRODUCTION & COST',title:'생산함수와 비용함수',lede:'생산량에 따라 달라지는 비용·매출·이익을 함수로 연결합니다.',terms:[['고정비용','생산량이 0이어도 드는 비용이에요.','가게 임대료나 기계 대여료가 대표적이에요.'],['변동비용','생산량이 늘면 함께 늘어나는 비용이에요.','빵 한 개마다 드는 밀가루와 포장지 비용이에요.'],['이익','판매로 들어온 매출에서 모든 비용을 뺀 금액이에요.','매출이 커도 비용이 더 크면 이익은 음수가 될 수 있어요.']],principle:'매출과 비용의 차이가 이익이에요',copy:'생산량 q, 한 개 가격 p, 단위당 변동비 v, 고정비 F라면 각 함수를 간단히 표현할 수 있습니다.',formula:'R(q)=pq<br>C(q)=F+vq<br>P(q)=R(q)−C(q)',example:'50개를 4,000원에 팔고 고정비 5만 원, 개당 비용 1,500원이면 이익은 75,000원입니다.',warning:'매출은 들어온 돈 전체이고 이익은 비용을 뺀 뒤 남은 돈입니다. 매출이 곧 이익은 아닙니다.',lab:'cost',quiz:['매출 30만 원, 고정비 5만 원, 변동비 18만 원일 때 이익은?',['7만 원','13만 원','23만 원'],0,'이익=30−5−18=7만 원입니다.']},
  market:{n:'07',chapter:'Ⅱ. 함수와 경제',color:'#287d8e',code:'DEMAND & SUPPLY',title:'수요함수와 공급함수',lede:'가격에 따라 소비자가 사려는 양과 생산자가 팔려는 양이 어떻게 달라지는지 그래프로 봅니다.',terms:[['수요량','특정 가격에서 소비자가 사려는 상품의 양이에요.','가격이 낮아지면 보통 더 많이 사려고 해요.'],['공급량','특정 가격에서 생산자가 팔려는 상품의 양이에요.','가격이 높아지면 보통 더 많이 공급하려고 해요.']],principle:'보통 수요는 내려가고 공급은 올라가요',copy:'다른 조건이 같다면 가격이 오를수록 수요량은 감소하고 공급량은 증가하는 관계를 일차함수로 단순화할 수 있습니다.',formula:'수요 Qd = a−bp<br>공급 Qs = c+dp',example:'Qd=100−p, Qs=20+p라면 p=40에서 둘 다 60이 됩니다.',warning:'수요와 수요량은 다릅니다. 가격만 바뀌면 곡선 위에서 수요량이 움직이고, 소득·선호 등이 바뀌면 수요곡선 자체가 이동합니다.',lab:'market',quiz:['다른 조건이 같을 때 가격이 오르면 일반적인 수요량은?',['증가한다.','감소한다.','반드시 그대로다.'],1,'일반적인 수요법칙에서는 가격이 오를수록 수요량이 감소합니다.']},
  utility:{n:'08',chapter:'Ⅱ. 함수와 경제',color:'#287d8e',code:'UTILITY',title:'효용함수',lede:'한정된 예산으로 여러 상품을 소비할 때 얻는 만족을 함수로 표현합니다.',terms:[['효용','상품이나 서비스를 소비하며 느끼는 만족의 정도를 수로 표현한 개념이에요.','같은 돈으로 어떤 조합을 고를 때 더 만족스러운지 비교해요.'],['예산제약','쓸 수 있는 돈 때문에 가능한 소비 조합이 제한되는 조건이에요.','가격×수량의 합이 가진 돈을 넘을 수 없어요.']],principle:'만족은 크되 예산 안에 있어야 해요',copy:'두 상품 x, y의 간단한 효용을 √(xy)로 두면 한 상품에만 몰기보다 두 상품을 적절히 섞을 때 만족이 커질 수 있습니다.',formula:'효용 U(x,y)=√(xy)<br>예산: pₓx+pᵧy ≤ M',example:'두 상품 가격이 같고 예산이 10이면 x=5, y=5에서 √25=5의 효용을 얻습니다.',warning:'효용의 숫자는 사람 사이의 행복을 직접 비교하는 점수가 아니라, 한 소비자의 선택 순서를 표현하기 위한 도구로 봅니다.',lab:'utility',quiz:['예산제약이 뜻하는 것은?',['만족은 언제나 최대여야 한다.','소비 지출이 가진 예산을 넘을 수 없다.','두 상품 수량은 반드시 같아야 한다.'],1,'예산제약은 가격×수량의 합이 사용 가능한 예산 이하여야 한다는 조건입니다.']},
  equilibrium:{n:'09',chapter:'Ⅱ. 함수와 경제',color:'#287d8e',code:'MARKET EQUILIBRIUM',title:'균형가격',lede:'수요량과 공급량이 같아져 초과수요나 초과공급이 사라지는 가격을 찾습니다.',terms:[['균형가격','사려는 양과 팔려는 양이 같아지는 가격이에요.','줄을 서도 물건이 모자라지 않고, 재고가 쌓이지도 않는 만남점이에요.'],['초과수요·초과공급','수요가 공급보다 많거나, 공급이 수요보다 많은 상태예요.','가격이 너무 낮으면 품절, 너무 높으면 재고가 생기기 쉬워요.']],principle:'두 함수가 같은 곳이 균형점이에요',copy:'수요함수와 공급함수를 같다고 놓아 가격을 구하고, 그 가격을 어느 함수에 대입해 균형거래량을 구합니다.',formula:'Qd = Qs<br>a−bp = c+dp',example:'Qd=100−p, Qs=20+p이면 100−p=20+p에서 p=40, Q=60입니다.',warning:'균형은 “모두가 원하는 최고의 가격”이라는 뜻이 아니라 수요량과 공급량이 일치하는 시장의 상태입니다.',lab:'equilibrium',quiz:['현재 가격에서 수요량 80, 공급량 50이라면?',['30의 초과수요','30의 초과공급','균형'],0,'사려는 양이 팔려는 양보다 30 많으므로 30의 초과수요입니다.']},
  feasible:{n:'10',chapter:'Ⅱ. 함수와 경제',color:'#287d8e',code:'FEASIBLE REGION',title:'균형 변화와 부등식 영역',lede:'소득·세금 변화가 균형을 움직이는 원리와 여러 조건을 동시에 만족하는 선택을 살펴봅니다.',terms:[['외생변수','모형 바깥에서 주어져 결과에 영향을 주는 조건이에요.','소득 증가나 세금 부과가 수요·공급곡선을 움직여요.'],['가능영역','여러 부등식을 동시에 만족하는 점들의 모임이에요.','예산·시간·재료 조건을 모두 지킨 생산 조합이에요.']],principle:'가능한 점 중 목적에 가장 맞는 점을 찾아요',copy:'생산량 x, y가 재료와 시간의 제한을 모두 만족해야 합니다. 각 부등식은 경계선의 한쪽 영역을 뜻합니다.',formula:'x ≥ 0, y ≥ 0<br>2x+y ≤ 재료<br>x+2y ≤ 시간',example:'재료 18, 시간 16일 때 x=6, y=5는 17≤18이고 16≤16이므로 가능한 조합입니다.',warning:'한 조건만 만족해서는 안 됩니다. 가능영역의 점은 모든 부등식을 동시에 만족해야 합니다.',lab:'feasible',quiz:['x=6, y=5일 때 2x+y≤18, x+2y≤16을 모두 만족하는가?',['만족한다.','첫 번째만 만족한다.','어느 것도 만족하지 않는다.'],0,'2×6+5=17≤18이고 6+2×5=16≤16이므로 모두 만족합니다.']},
  matrix:{n:'11',chapter:'Ⅲ. 행렬과 경제',color:'#6856a5',code:'MATRIX',title:'행렬과 경제 현상',lede:'지점과 상품이 많은 자료를 행과 열로 정리하고 행렬의 곱으로 매출을 한꺼번에 계산합니다.',terms:[['행렬','수를 직사각형 모양으로 배열해 한 덩어리로 다루는 방법이에요.','행을 지점, 열을 상품으로 두면 판매표가 행렬이 돼요.'],['행렬의 곱','앞 행렬의 행과 뒤 행렬의 열을 짝지어 곱하고 더하는 계산이에요.','각 지점의 상품 수량과 가격을 묶어 총매출을 계산해요.']],principle:'행과 열에 붙인 의미를 먼저 확인해요',copy:'판매량 행렬의 한 행과 가격 열행렬을 곱하면 그 지점의 총매출이 됩니다.',formula:'[수량 행렬] × [가격 열행렬]<br>= [지점별 매출]',example:'학교점이 A 30개, B 20개를 팔고 가격이 3,000원, 5,000원이면 매출은 190,000원입니다.',warning:'행렬의 곱은 같은 위치끼리만 곱하는 계산이 아닙니다. 앞 행의 값과 뒤 열의 값을 짝지어 곱한 뒤 더합니다.',lab:'matrix',quiz:['판매량 행렬의 행이 지점, 열이 상품이라면 2행 1열은?',['1번 지점의 2번 상품','2번 지점의 1번 상품','상품 가격'],1,'행은 지점, 열은 상품이므로 2행 1열은 2번 지점의 1번 상품 수량입니다.']},
  inverse:{n:'12',chapter:'Ⅲ. 행렬과 경제',color:'#6856a5',code:'INVERSE MATRIX',title:'역행렬과 활용',lede:'행렬의 곱셈을 되돌리는 역행렬로 알려진 결과에서 미지의 값을 구합니다.',terms:[['역행렬','어떤 행렬과 곱했을 때 단위행렬이 되어 원래 계산을 되돌리는 행렬이에요.','곱셈에서 나눗셈과 비슷한 역할을 해요.'],['행렬식','2×2 행렬이 역행렬을 갖는지 알려주는 값이에요.','ad−bc가 0이면 정보를 되돌릴 수 없어요.']],principle:'행렬식이 0이 아니어야 되돌릴 수 있어요',copy:'A=[[a,b],[c,d]]의 행렬식 ad−bc가 0이 아니면 역행렬이 존재합니다.',formula:'det(A)=ad−bc<br>A⁻¹=1/(ad−bc)[[d,−b],[−c,a]]',example:'A=[[2,1],[1,1]]이면 det(A)=1이고 역행렬은 [[1,−1],[−1,2]]입니다.',warning:'행렬식이 0이면 역행렬이 없습니다. 서로 다른 정보처럼 보이는 두 식이 실제로 같은 관계를 나타낼 수 있기 때문입니다.',lab:'inverse',quiz:['2×2 행렬의 행렬식 ad−bc가 0이면?',['항상 역행렬이 있다.','역행렬이 없다.','모든 원소가 0이다.'],1,'행렬식이 0인 행렬은 역행렬을 갖지 않습니다.']},
  derivative:{n:'13',chapter:'Ⅳ. 미분과 경제',color:'#36805a',code:'MARGINAL CHANGE',title:'미분과 그래프 개형',lede:'경제함수의 순간변화율을 한계량으로 해석하고 증가·감소를 그래프와 연결합니다.',terms:[['한계','어떤 양을 한 단위 더 늘릴 때 결과가 얼마나 변하는지 보는 관점이에요.','빵 한 개를 더 만들 때 추가되는 비용이 한계비용이에요.'],['한계이익','생산량을 아주 조금 늘릴 때 이익이 얼마나 변하는지 나타내요.','양수면 더 만들수록 이익이 늘고, 음수면 줄어들어요.']],principle:'도함수의 부호가 원래 함수의 방향을 알려줘요',copy:'이익함수 P(q)를 미분한 P′(q)는 생산량 q 근처의 한계이익입니다.',formula:'한계이익 = P′(q)<br>P′(q)>0 증가, P′(q)<0 감소',example:'P(q)=−q²+80q−400이면 P′(q)=−2q+80이고 q=40에서 0입니다.',warning:'도함수가 0인 모든 점이 반드시 최대는 아닙니다. 앞뒤에서 도함수의 부호가 +에서 −로 바뀌는지 확인해야 합니다.',lab:'derivative',quiz:["P′(q)가 양수인 구간에서 생산량 q가 늘어나면 이익 P(q)는?",['증가한다.','감소한다.','항상 0이다.'],0,'도함수가 양수이면 원래 함수는 그 구간에서 증가합니다.']},
  elasticity:{n:'14',chapter:'Ⅳ. 미분과 경제',color:'#36805a',code:'ELASTICITY',title:'탄력성',lede:'가격의 상대적 변화에 수요량이 얼마나 민감하게 반응하는지 비율로 측정합니다.',terms:[['가격탄력성','가격이 1% 변할 때 수요량이 몇 % 변하는지 나타내는 민감도예요.','가격을 조금 올렸는데 수요가 크게 줄면 탄력적이에요.'],['탄력적·비탄력적','탄력성의 절댓값이 1보다 크거나 작은 상태예요.','필수품은 비교적 비탄력적, 대체품이 많으면 탄력적일 수 있어요.']],principle:'단위가 아니라 퍼센트 변화끼리 비교해요',copy:'가격 변화율에 대한 수요량 변화율의 비가 가격탄력성입니다. 수요는 대체로 가격과 반대로 움직여 음수가 되므로 절댓값을 자주 사용합니다.',formula:'E = 수요량 변화율 ÷ 가격 변화율',example:'가격이 10% 오를 때 수요량이 20% 줄면 E=−2, 절댓값 2로 탄력적입니다.',warning:'가격이 100원 변한 것과 수요량이 100개 변한 것을 바로 나누면 단위에 따라 값이 달라집니다. 반드시 변화율을 비교합니다.',lab:'elasticity',quiz:['가격 5% 상승, 수요량 15% 감소라면 탄력성의 절댓값은?',['0.33','3','10'],1,'|−15%÷5%|=3이므로 탄력적입니다.']},
  optimization:{n:'15',chapter:'Ⅳ. 미분과 경제',color:'#36805a',code:'OPTIMIZATION',title:'최적화',lede:'함수와 미분을 이용해 이익이 가장 큰 가격이나 생산량을 찾습니다.',terms:[['최적화','주어진 조건 안에서 목적함수를 가장 크게 또는 작게 만드는 선택을 찾는 과정이에요.','같은 재료로 이익이 가장 큰 생산량을 찾는 일이에요.'],['목적함수','최대화하거나 최소화하려는 결과를 나타낸 함수예요.','기업의 이익, 소비자의 효용, 운송비용 등이 될 수 있어요.']],principle:'꼭대기 후보를 찾고 조건 안에서 비교해요',copy:'미분 가능한 이익함수에서는 도함수가 0인 지점이 최대 후보입니다. 정의역의 끝점도 함께 비교해야 합니다.',formula:'P′(q)=0인 후보 찾기<br>후보와 끝점의 P(q) 비교',example:'P(q)=−q²+80q−400은 q=40에서 최대 이익 1,200을 갖습니다.',warning:'수학적 최대점이 현실에서 항상 가능한 것은 아닙니다. 생산능력, 정수 수량, 법과 윤리 같은 조건도 확인해야 합니다.',lab:'optimization',quiz:['아래로 열린 이차 이익함수의 도함수가 q=40에서 0이라면 최대 후보 생산량은?',['0','40','80'],1,'아래로 열린 이차함수의 꼭짓점이므로 q=40이 최대 후보입니다.']}
};

const order=Object.keys(topics);const params=new URLSearchParams(location.search);const id=topics[params.get('id')]?params.get('id'):'indicator';const t=topics[id];document.documentElement.style.setProperty('--accent',t.color);document.title=`${t.title} · 경제수학 · JP Math Lab`;
const $=s=>document.querySelector(s);$('[data-code]').textContent=`${t.n} · ${t.code}`;$('[data-title]').textContent=t.title;$('[data-lede]').textContent=t.lede;$('[data-chapter]').textContent=t.chapter;$('[data-principle-title]').textContent=t.principle;$('[data-principle-copy]').textContent=t.copy;$('[data-formula]').innerHTML=t.formula;$('[data-example]').textContent=t.example;$('[data-warning]').textContent=t.warning;$('[data-lab-title]').textContent=`${t.title} 실험실`;
$('[data-terms]').innerHTML=t.terms.map((x,i)=>`<article class="term-card"><header><h3>${x[0]}</h3><span>WORD ${String(i+1).padStart(2,'0')}</span></header><p>${x[1]}</p><aside><b>생활 장면</b> · ${x[2]}</aside></article>`).join('');

function showTab(key){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===key));document.querySelectorAll('[data-panel]').forEach(p=>{const on=p.dataset.panel===key;p.hidden=!on;p.classList.toggle('active',on)});scrollTo({top:document.querySelector('.tabs').offsetTop-12,behavior:'smooth'})}document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showTab(b.dataset.go));
const won=n=>`${Math.round(n).toLocaleString('ko-KR')}원`;const num=n=>Number(n).toLocaleString('ko-KR',{maximumFractionDigits:2});const lab=$('[data-lab]');
const range=(label,name,min,max,value,step=1,suffix='')=>`<label class="control"><span>${label}<output data-o="${name}">${num(value)}${suffix}</output></span><input type="range" min="${min}" max="${max}" value="${value}" step="${step}" data-i="${name}"></label>`;
const number=(label,name,value,min=0,step=1)=>`<label class="control"><span>${label}</span><input type="number" value="${value}" min="${min}" step="${step}" data-i="${name}"></label>`;
const board=(items)=>`<div class="result-board">${items.map((x,i)=>`<div${i===items.length-1?' class="accent"':''}><small>${x[0]}</small><strong data-r="${x[1]}">-</strong></div>`).join('')}</div><p class="coach" data-coach></p>`;
function bind(calc){lab.querySelectorAll('[data-i]').forEach(input=>input.addEventListener('input',()=>{const out=lab.querySelector(`[data-o="${input.dataset.i}"]`);if(out)out.textContent=num(input.value)+(input.dataset.i==='rate'||input.dataset.i==='growth'?'%':'');calc()}));calc()}
function setR(k,v){const e=lab.querySelector(`[data-r="${k}"]`);if(e)e.textContent=v}function val(k){return Number(lab.querySelector(`[data-i="${k}"]`).value)||0}function coach(s){lab.querySelector('[data-coach]').textContent=s}

const labs={
indicator(){lab.innerHTML=`<div class="control-grid two">${range('이전 퍼센트','old',1,20,4,.5,'%')}${range('새 퍼센트','new',1,20,6,.5,'%')}</div>${board([['단순한 차이','point'],['처음 값 대비 변화율','change']])}`;bind(()=>{const a=val('old'),b=val('new'),d=b-a;setR('point',`${num(d)}%p`);setR('change',`${num(d/a*100)}%`);coach(`${a}%에서 ${b}%로 변하면 ${num(d)}%포인트, 처음 값에 비해서는 ${num(d/a*100)}% 변화입니다.`)})},
exchange(){lab.innerHTML=`<div class="control-grid two">${range('환전할 달러','dollar',10,1000,100,10,'달러')}${range('1달러당 환율','ratex',900,1800,1380,10,'원')}</div>${board([['필요한 원화','krw'],['환율 100원 상승 시 추가금','extra']])}`;bind(()=>{const d=val('dollar'),r=val('ratex');setR('krw',won(d*r));setR('extra',won(d*100));coach(`환율 ${num(r)}원에서 ${num(d)}달러를 사려면 ${won(d*r)}이 필요합니다.`)})},
tax(){lab.innerHTML=`<div class="control-grid two">${range('세전 가격','price',1000,100000,8000,1000,'원')}${range('세율','rate',0,30,10,1,'%')}</div>${board([['세금','tax'],['세후 가격','total']])}`;bind(()=>{const p=val('price'),r=val('rate')/100;setR('tax',won(p*r));setR('total',won(p*(1+r)));coach(`${p.toLocaleString()}×${r}=${(p*r).toLocaleString()}이므로 세후 가격은 ${won(p*(1+r))}입니다.`)})},
sequence(){lab.innerHTML=`<div class="control-grid">${range('첫째 항','first',1,100,10,1)}${range('공차','diff',-10,20,2,1)}${range('몇 번째 항','nth',1,20,6,1)}</div>${board([['n번째 항','term'],['첫 항부터 n항까지 합','sum']])}`;bind(()=>{const a=val('first'),d=val('diff'),n=val('nth');setR('term',num(a+(n-1)*d));setR('sum',num(n*(2*a+(n-1)*d)/2));coach(`${n}번째 항은 ${a}+(${n}−1)×${d}=${a+(n-1)*d}입니다.`)})},
finance(){lab.innerHTML=`<div class="control-grid">${range('원금','principal',100000,5000000,1000000,100000,'원')}${range('연 이자율','rate',1,15,5,.5,'%')}${range('기간','years',1,20,3,1,'년')}</div>${board([['단리 원리합계','simple'],['복리 원리합계','compound'],['복리의 추가 이자','gap']])}`;bind(()=>{const p=val('principal'),r=val('rate')/100,n=val('years'),s=p*(1+r*n),c=p*(1+r)**n;setR('simple',won(s));setR('compound',won(c));setR('gap',won(c-s));coach(`${n}년 뒤 복리는 ${won(c)}으로, 같은 조건의 단리보다 ${won(c-s)} 더 큽니다.`)})},
cost(){lab.innerHTML=`<div class="control-grid">${range('생산·판매량','q',0,150,50,5,'개')}${range('한 개 가격','unitprice',1000,8000,4000,100,'원')}${range('한 개 변동비','variable',500,5000,1500,100,'원')}</div>${board([['매출','revenue'],['총비용 (고정비 5만원)','cost'],['이익','profit']])}`;bind(()=>{const q=val('q'),p=val('unitprice'),v=val('variable'),r=q*p,c=50000+q*v;setR('revenue',won(r));setR('cost',won(c));setR('profit',won(r-c));coach(r-c>=0?`매출에서 비용을 빼면 ${won(r-c)}이 남습니다.`:`비용이 매출보다 ${won(c-r)} 큽니다. 손익분기점을 넘지 못했습니다.`)})},
market(){marketLab(false)},equilibrium(){marketLab(true)},
utility(){lab.innerHTML=`<div class="control-grid two">${range('상품 A 수량 (개당 2)','x',0,10,5,1,'개')}${range('상품 B 수량 (개당 1)','y',0,20,10,1,'개')}</div>${board([['총지출','spend'],['예산 20의 남은 돈','left'],['효용 √(xy)','utility']])}`;bind(()=>{const x=val('x'),y=val('y'),s=2*x+y;setR('spend',num(s));setR('left',num(20-s));setR('utility',num(Math.sqrt(x*y)));coach(s<=20?`예산 안의 소비 조합입니다. 효용은 ${num(Math.sqrt(x*y))}입니다.`:`예산을 ${num(s-20)}만큼 초과했습니다. 가능한 소비 조합이 아닙니다.`)})},
feasible(){lab.innerHTML=`<div class="control-grid two">${range('상품 A 생산량 x','x',0,12,6,1,'개')}${range('상품 B 생산량 y','y',0,12,5,1,'개')}</div>${board([['재료 사용 2x+y / 18','material'],['시간 사용 x+2y / 16','time'],['예상 이익 3x+4y','profit']])}`;bind(()=>{const x=val('x'),y=val('y'),m=2*x+y,h=x+2*y,ok=m<=18&&h<=16;setR('material',num(m));setR('time',num(h));setR('profit',num(3*x+4*y));coach(ok?'두 제약을 모두 만족하는 가능영역 안의 점입니다.':'적어도 한 제약을 넘었습니다. 가능영역 밖의 점입니다.')})},
matrix(){lab.innerHTML=`<div class="matrix-row"><div class="matrix-label"><small>판매량 Q</small><div class="matrix"><input data-i="a" type="number" value="30"><input data-i="b" type="number" value="20"><input data-i="c" type="number" value="18"><input data-i="d" type="number" value="28"></div></div><span class="op">×</span><div class="matrix-label"><small>가격 P</small><div class="matrix one-col"><input data-i="p1" type="number" value="3000"><input data-i="p2" type="number" value="5000"></div></div><span class="op">=</span><div class="matrix-label"><small>지점별 매출</small><div class="matrix one-col"><output data-r="r1"></output><output data-r="r2"></output></div></div></div><p class="coach" data-coach></p>`;bind(()=>{const r1=val('a')*val('p1')+val('b')*val('p2'),r2=val('c')*val('p1')+val('d')*val('p2');setR('r1',won(r1));setR('r2',won(r2));coach(`첫째 행은 1번 지점 매출 ${won(r1)}, 둘째 행은 2번 지점 매출 ${won(r2)}이 됩니다.`)})},
inverse(){lab.innerHTML=`<div class="matrix-row"><div class="matrix-label"><small>행렬 A</small><div class="matrix"><input data-i="a" type="number" value="2"><input data-i="b" type="number" value="1"><input data-i="c" type="number" value="1"><input data-i="d" type="number" value="1"></div></div><span class="op">→</span><div class="matrix-label"><small>역행렬 A⁻¹</small><div class="matrix"><output data-r="i1"></output><output data-r="i2"></output><output data-r="i3"></output><output data-r="i4"></output></div></div></div>${board([['행렬식 ad−bc','det']])}`;bind(()=>{const a=val('a'),b=val('b'),c=val('c'),d=val('d'),det=a*d-b*c;setR('det',num(det));if(det){[['i1',d/det],['i2',-b/det],['i3',-c/det],['i4',a/det]].forEach(x=>setR(x[0],num(x[1])));coach(`행렬식이 ${det}로 0이 아니므로 역행렬이 있습니다.`)}else{['i1','i2','i3','i4'].forEach(k=>setR(k,'없음'));coach('행렬식이 0이므로 역행렬이 없습니다.')}})},
derivative(){curveLab(false)},optimization(){curveLab(true)},
elasticity(){lab.innerHTML=`<div class="control-grid">${range('가격 변화율','pchange',-30,30,10,1,'%')}${range('수요량 변화율','qchange',-50,50,-20,1,'%')}</div>${board([['탄력성 E','e'],['탄력성 절댓값','abs'],['판정','type']])}`;bind(()=>{const p=val('pchange'),q=val('qchange');if(!p){setR('e','정의 안 됨');setR('abs','-');setR('type','-');coach('가격 변화율이 0이면 이 비율로 탄력성을 계산할 수 없습니다.');return}const e=q/p,a=Math.abs(e);setR('e',num(e));setR('abs',num(a));setR('type',a>1?'탄력적':a<1?'비탄력적':'단위탄력적');coach(`수요량 변화율 ${q}%를 가격 변화율 ${p}%로 나눈 값은 ${num(e)}입니다.`)})}
};
function marketLab(equilibrium){lab.innerHTML=`<div class="control-grid two">${range('수요 절편 a','demanda',70,140,100,5)}${range('공급 절편 c','supplyc',0,60,20,5)}</div><canvas class="math-canvas" width="820" height="300" data-canvas></canvas>${board([['균형가격','ep'],['균형거래량','eq']])}`;const draw=()=>{const a=val('demanda'),c=val('supplyc'),p=(a-c)/2,q=(a+c)/2;setR('ep',num(p));setR('eq',num(q));coach(equilibrium?`Qd=Qs가 되는 가격은 ${num(p)}, 거래량은 ${num(q)}입니다.`:`수요곡선은 내려가고 공급곡선은 올라가며 (${num(q)}, ${num(p)})에서 만납니다.`);const cv=lab.querySelector('canvas'),x=cv.getContext('2d'),W=cv.width,H=cv.height,pad=45;x.clearRect(0,0,W,H);x.strokeStyle='#d9ded9';x.lineWidth=1;for(let i=0;i<6;i++){const yy=pad+i*(H-2*pad)/5;x.beginPath();x.moveTo(pad,yy);x.lineTo(W-pad,yy);x.stroke()}x.strokeStyle='#44534b';x.lineWidth=2;x.beginPath();x.moveTo(pad,H-pad);x.lineTo(W-pad,H-pad);x.moveTo(pad,H-pad);x.lineTo(pad,pad);x.stroke();const sx=v=>pad+v/140*(W-2*pad),sy=v=>H-pad-v/100*(H-2*pad);x.strokeStyle='#d4673a';x.lineWidth=4;x.beginPath();x.moveTo(sx(Math.max(0,a-100)),sy(100));x.lineTo(sx(a),sy(0));x.stroke();x.strokeStyle='#287d8e';x.beginPath();x.moveTo(sx(Math.max(0,c)),sy(0));x.lineTo(sx(Math.min(140,c+100)),sy(100));x.stroke();x.fillStyle='#17211d';x.beginPath();x.arc(sx(q),sy(p),7,0,Math.PI*2);x.fill();x.font='600 13px IBM Plex Sans KR';x.fillText('균형',sx(q)+11,sy(p)-10)};bind(draw)}
function curveLab(opt){lab.innerHTML=`<div class="control-grid two">${range('생산량 q','q',0,80,opt?40:25,1,'개')}${range('수요 강도 a','strength',60,100,80,5)}</div><canvas class="math-canvas" width="820" height="300" data-canvas></canvas>${board([['현재 이익 P(q)','profit'],['한계이익 P′(q)','marginal'],['최적 생산량','optimal']])}`;const draw=()=>{const q=val('q'),a=val('strength'),P=x=>-x*x+a*x-400,M=x=>-2*x+a,o=a/2;setR('profit',num(P(q)));setR('marginal',num(M(q)));setR('optimal',num(o));coach(Math.abs(q-o)<2?'한계이익이 0에 가까운 이익의 꼭대기입니다.':q<o?'한계이익이 양수라 생산량을 늘리면 이익이 증가합니다.':'한계이익이 음수라 생산량을 더 늘리면 이익이 감소합니다.');const cv=lab.querySelector('canvas'),c=cv.getContext('2d'),W=cv.width,H=cv.height,pad=45,min=-500,max=1800,sx=x=>pad+x/80*(W-2*pad),sy=y=>H-pad-(y-min)/(max-min)*(H-2*pad);c.clearRect(0,0,W,H);c.strokeStyle='#d9ded9';c.lineWidth=1;for(let i=0;i<6;i++){let yy=pad+i*(H-2*pad)/5;c.beginPath();c.moveTo(pad,yy);c.lineTo(W-pad,yy);c.stroke()}c.strokeStyle='#36805a';c.lineWidth=4;c.beginPath();for(let x=0;x<=80;x++){const X=sx(x),Y=sy(P(x));x?c.lineTo(X,Y):c.moveTo(X,Y)}c.stroke();c.fillStyle='#d4673a';c.beginPath();c.arc(sx(q),sy(P(q)),7,0,Math.PI*2);c.fill();c.fillStyle='#17211d';c.font='600 13px IBM Plex Sans KR';c.fillText(`q=${q}`,sx(q)+10,sy(P(q))-9)};bind(draw)}
(labs[t.lab]||labs.indicator)();

const [question,choices,correct,explain]=t.quiz;$('[data-question]').textContent=question;const answers=$('[data-answers]');function renderAnswers(){answers.innerHTML=choices.map((x,i)=>`<button type="button" data-choice="${i}">${String.fromCharCode(65+i)}. ${x}</button>`).join('');$('[data-feedback]').hidden=true;answers.querySelectorAll('button').forEach(b=>b.onclick=()=>answer(Number(b.dataset.choice)))}function answer(choice){answers.querySelectorAll('button').forEach((b,i)=>{b.disabled=true;b.classList.toggle('correct',i===correct);b.classList.toggle('wrong',i===choice&&choice!==correct)});const f=$('[data-feedback]');f.hidden=false;f.classList.toggle('wrong',choice!==correct);f.innerHTML=`<b>${choice===correct?'정답입니다!':'다시 원리를 연결해 봅시다.'}</b><br>${explain}`}renderAnswers();$('[data-retry]').onclick=renderAnswers;const ni=order.indexOf(id)+1,next=$('[data-next-topic]');if(ni<order.length)next.href=`경제수학_학습.html?id=${order[ni]}`;else{next.href='교과서학습.html';next.textContent='개념 목록으로 →'}
